force-app/main/default/objects/Bundle__c/Bundle__c.object-meta.xml
<CustomObject>
    <description>Represents a bundle of products that are marketed, priced and sold as a unit</description>
    <label>Bundle</label>
    <nameField>
        <label>Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The bundle that this discount is restricted to.</description>
    <label>Bundle</label>
    <referenceTo>Bundle__c</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Order_Builder_Visible__c.field-meta.xml
<CustomField>
    <fullName>Order_Builder_Visible__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This product is directly available in Order Builder.</description>
    <label>Order Builder Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Is_Biobanking_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_Biobanking_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if this is a Biobanking product OR a bundle including Biobanking product(s)</description>
    <inlineHelpText>True if this is a Biobanking product OR a bundle including Biobanking product(s)</inlineHelpText>
    <label>Is Biobanking Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Relationship__c/Product_Relationship__c.object-meta.xml
<CustomObject>
    <description>Allows us to create relationships between products to define things such as suggested upsells or required add-ons.</description>
    <label>Product Relationship</label>
    <nameField>
        <displayFormat>PRN-{000000}</displayFormat>
        <label>Product Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Relationship__c/fields/Primary_Product__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary product in this relationship.</description>
    <label>Primary Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Related Products</relationshipLabel>
    <relationshipName>Related_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Relationship__c/fields/Related_Product__c.field-meta.xml
<CustomField>
    <fullName>Related_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The secondary product in this relationship</description>
    <label>Related Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Products</relationshipLabel>
    <relationshipName>Parent_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Relationship__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required Add-On</fullName>
            </value>
            <value>
                <fullName>Suggested Upsell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderBuilderTestFactory.cls
@isTest
public class OrderBuilderTestFactory {
    
    
    public static void createProductSuite() {
        System.debug('createProductSuite: ');
        
        // Setup PriceBooks
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        update standardPricebook;
        System.debug('updated standardPricebook: '+standardPricebook.Id);

        Id standardPriceBookId = Test.getStandardPricebookId();
        System.debug('standardPriceBookId: '+standardPriceBookId);
        // Pricebook2 customPriceBook = new Pricebook2 (Name = 'Test PB', 
        //                                              Description = 'Test', 
        //                                              IsActive = true );
        // insert customPriceBook;
        // Id customPriceBookId = customPriceBook.Id;

        List < Product2 > productsToInsert = new List < Product2 > ();
        for (Integer i = 0; i < 10; i++) {
            Product2 product = Test_ProductFactory.start()
                .overrideName('Test Product ' + i)
                .asBiobanking()
                .asEligibleForVolumeDiscounting()
                .build();
            productsToInsert.add(product);

            Product2 storageProduct = Test_ProductFactory.start()
                .overrideName('Test Product ' + i + ' Storage')
                .asStorage()
                .build();
            productsToInsert.add(storageProduct);
        }

        //Specifically add CB 20 and CT20
        Product2 cbp = Test_ProductFactory.start()
            .overrideName('Cord Blood Processing')
            .asBiobanking()
            .asEligibleForVolumeDiscounting()
            .build();
        productsToInsert.add(cbp);

        Product2 cbStorage = Test_ProductFactory.start()
            .overrideName('Cord Blood 20yr Storage')
            .asStorage()
            .build();
        productsToInsert.add(cbStorage);

        Product2 ctp = Test_ProductFactory.start()
            .overrideName('Cord Tissue Processing')
            .asBiobanking()
            .asEligibleForVolumeDiscounting()
            .build();
        productsToInsert.add(ctp);

        Product2 ctStorage = Test_ProductFactory.start()
            .overrideName('Cord Tissue 20yr Storage')
            .asStorage()
            .build();
        productsToInsert.add(ctStorage);

        Product2 shippingProduct = Test_ProductFactory.start()
            .overrideName('Standard Shipping')
            .asShipping()
            .build();
        productsToInsert.add(shippingProduct);

        Product2 kitProduct = Test_ProductFactory.start()
            .asKit()
            .build();
        productsToInsert.add(kitProduct);

        Product2 dueAtCheckout = Test_ProductFactory.start()
            .asDueAtCheckout()
            .build();
        productsToInsert.add(dueAtCheckout);

        Product2 partialDueAtCheckout = Test_ProductFactory.start()
            .withPartialAmtDueAtCheckout(50)
            .build();
        productsToInsert.add(partialDueAtCheckout);

        Product2 interestFeeProduct12 = Test_ProductFactory.start()
            .asFee()
            .overrideName('Total Monthly Fees - 12M')
            .build();
        productsToInsert.add(interestFeeProduct12);

        Product2 interestFeeProduct24 = Test_ProductFactory.start()
            .asFee()
            .overrideName('Total Monthly Fees - 24M')
            .build();
        productsToInsert.add(interestFeeProduct24);
        
        Product2 interestFeeProduct36 = Test_ProductFactory.start()
            .asFee()
            .overrideName('Total Monthly Fees - 36M')
            .build();
        productsToInsert.add(interestFeeProduct36);

        Product2 interestFeeProduct48 = Test_ProductFactory.start()
            .asFee()
            .overrideName('Total Monthly Fees - 48M')
            .build();
        productsToInsert.add(interestFeeProduct48);

        insert productsToInsert;      
        
        //Pull out kit and shipping products with ids to create related product relationships
        Product2 kit;
        Product2 shipping;
        for (Product2 product: productsToInsert) {
            if (product.Family == 'Add-on') {
                kit = product;
            }
            if (product.Family == 'Shipping') {
                shipping = product;
            }
        }

        //add related required
        List <Product_Relationship__c> productRelationships = new List <Product_Relationship__c> ();
        for (Product2 product: productsToInsert) {
            if (product.Family == 'Product' && product.Is_Biobanking_Product__c == true) {
                Product_Relationship__c productRelationship = new Product_Relationship__c(
                    Primary_Product__c = product.Id,
                    Related_Product__c = kit.Id,
                    Relationship__c = 'Required Add-On'
                );
                productRelationships.add(productRelationship);

                Product_Relationship__c productRelationship2 = new Product_Relationship__c(
                    Primary_Product__c = product.Id,
                    Related_Product__c = shipping.Id,
                    Relationship__c = 'Required Add-On'
                );
                productRelationships.add(productRelationship2);
            }
        }
        insert productRelationships;


        // Create Pricebook Entries
        List < PricebookEntry > pricebookEntriesForInsert = new List < PricebookEntry > ();

        for (Product2 product: productsToInsert) {
            PricebookEntry standardPricebookEntry = new PricebookEntry(
                Pricebook2Id = standardPriceBookId,
                Product2Id = product.Id,
                UnitPrice = 100,
                IsActive = true
            );
            pricebookEntriesForInsert.add(standardPricebookEntry);
        }

        //Make one of the products order-builder visible on its own
        pricebookEntriesForInsert[0].Order_Builder_Visible__c = true;
        insert pricebookEntriesForInsert;
        System.debug('inserted pricebook entries: '+JSON.serialize(pricebookEntriesForInsert));

        // Create Bundles
        //Get a list of products to add to a Single Product bundle
        List < Product2 > productsForCBBundle = new List < Product2 > ();
        for (Product2 product: productsToInsert) {
            if (product.name == 'Cord Blood Processing' || product.name == 'Cord Blood 20yr Storage') {
                productsForCBBundle.add(product);
            }
        }

        Bundle__c singleProductBundle = Test_BundleFactory.start()
            .asSingleProduct()
            .createWithBundleMembers(productsForCBBundle, 150.0);

        //Get a list of products to add to a Multi Product bundle
        List < Product2 > productsForMultiBundle = new List < Product2 > ();
        for (Product2 product: productsToInsert) {
            if (product.name == 'Cord Blood Processing' || product.name == 'Cord Blood 20yr Storage' || product.name == 'Cord Tissue Processing' || product.name == 'Cord Tissue 20yr Storage') {
                productsForMultiBundle.add(product);
            }
        }

        Bundle__c multiProductBundle = Test_BundleFactory.start()
            .asMultiProduct()
            .createWithBundleMembers(productsForMultiBundle, 300.0);

        // create a Discount of type sales  
        List < Discount__c > discountsToInsert = new List < Discount__c > ();

        Discount__c wholeOrderAmountSales = Test_DiscountFactory.start()
            .amountBased(10.0)
            .asWholeOrder()
            .asSales()
            .build();
        discountsToInsert.add(wholeOrderAmountSales);

        Discount__c wholeOrderPercentageSales = Test_DiscountFactory.start()
            .percentageBased(.1)
            .asWholeOrder()
            .asSales()
            .build();
        discountsToInsert.add(wholeOrderPercentageSales);

        Discount__c wholeOrderAmountMarketing = Test_DiscountFactory.start()
            .amountBased(10.0)
            .asWholeOrder()
            .withCode('TestCode')
            .build();
        discountsToInsert.add(wholeOrderAmountMarketing);

        Discount__c wholeOrderPercentageMarketing = Test_DiscountFactory.start()
            .percentageBased(.1)
            .asWholeOrder()
            .withCode('TestCode')
            .build();
        discountsToInsert.add(wholeOrderPercentageMarketing);

        Discount__c productSpecificAmountSales = Test_DiscountFactory.start()
            .amountBased(10.0)
            .asProductSpecific(productsToInsert[0].Id)
            .build();
        discountsToInsert.add(productSpecificAmountSales);

        Discount__c productSpecificPercentageSales = Test_DiscountFactory.start()
            .percentageBased(.1)
            .asProductSpecific(productsToInsert[0].Id)
            .build();   
        discountsToInsert.add(productSpecificPercentageSales);

        Discount__c bundleSpecificAmountSales = Test_DiscountFactory.start()
            .amountBased(10.0)
            .asBundleSpecific(multiProductBundle.Id)
            .build();   
        discountsToInsert.add(bundleSpecificAmountSales);

        Discount__c bundleSpecificPercentageSales = Test_DiscountFactory.start()
            .percentageBased(.1)
            .asBundleSpecific(multiProductBundle.Id)
            .build();
        discountsToInsert.add(bundleSpecificPercentageSales);

        Discount__c multiBiobankingDiscount = Test_DiscountFactory.start()
            .amountBased(10.0)
            .asMultiBiobanking(2)
            .setApplicableStorageType('20YPP')
            .build();   
        discountsToInsert.add(multiBiobankingDiscount);

        insert discountsToInsert;

    }


}