force-app/main/default/objects/Bundle__c/Bundle__c.object-meta.xml
<CustomObject>
    <description>Represents a bundle of products that are marketed, priced and sold as a unit</description>
    <label>Bundle</label>
    <nameField>
        <label>Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle__c/fields/Storage_Type__c.field-meta.xml
<CustomField>
    <fullName>Storage_Type__c</fullName>
    <description>The storage type for the item in this single-product bundle.</description>
    <inlineHelpText>The storage type for the item in this single-product bundle.</inlineHelpText>
    <label>Storage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Storage_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bundle__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Affects how bundles are shown and filtered in the Order Builder.</description>
    <inlineHelpText>Single-Product bundles contain storage + processing for one service.  Multi-Product bundles contain two or more services or products.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single-Product</fullName>
            </value>
            <value>
                <fullName>Multi-Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bundle__c/fields/Valid_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_From_Date__c</fullName>
    <label>Valid From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bundle__c/fields/Valid_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_To_Date__c</fullName>
    <label>Valid To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bundle_Member__c/Bundle_Member__c.object-meta.xml
<CustomObject>
    <description>Join object that relates Products to Bundles</description>
    <label>Bundle Member</label>
    <nameField>
        <displayFormat>BMN-{000000}</displayFormat>
        <label>Bundle Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Member__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <description>The bundle that this bundle-member applied to</description>
    <label>Bundle</label>
    <referenceTo>Bundle__c</referenceTo>
    <relationshipLabel>Bundle Members</relationshipLabel>
    <relationshipName>Bundle_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bundle_Member__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product that this bundle member adds. Ideally this would be required at the field level, but Product lookups cannot be made required -- SF limitation.</description>
    <inlineHelpText>Required!</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Members</relationshipLabel>
    <relationshipName>Bundle_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bundle_Member__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>How many of this line item are represented in the bundle.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/Bundle_Pricebook_Entry__c.object-meta.xml
<CustomObject>
    <label>Bundle Pricebook Entry</label>
    <nameField>
        <displayFormat>BPE-{000000}</displayFormat>
        <label>Pricebook Entry Bundle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Pricebook Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <label>Bundle</label>
    <referenceTo>Bundle__c</referenceTo>
    <relationshipLabel>Bundle Pricebook Entries</relationshipLabel>
    <relationshipName>Bundle_Pricebook_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>Marketing price for the bundle in this pricebook</description>
    <label>List Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/fields/Order_Builder_Visible__c.field-meta.xml
<CustomField>
    <fullName>Order_Builder_Visible__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This product is directly available in Order Builder.</description>
    <label>Order Builder Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Bundle Pricebook Entries</relationshipLabel>
    <relationshipName>Bundle_Pricebook_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Dollar amount of the discount.</description>
    <inlineHelpText>The dollar amount of the discount. Only select if the Method is Amount.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The bundle that this discount is restricted to.</description>
    <label>Bundle</label>
    <referenceTo>Bundle__c</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Product that this discount is restricted to.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bundle Specific</fullName>
            </value>
            <value>
                <fullName>Product Specific</fullName>
            </value>
            <value>
                <fullName>Whole Order</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Multi-Annual Storage</fullName>
            </value>
            <value>
                <fullName>Multi-Biobanking Pkg</fullName>
            </value>
            <value>
                <fullName>Ad-Hoc Sales</fullName>
                <isActive>false</isActive>
                <label>Ad-Hoc Sales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>The total of all the list prices of bundles and products in this Opportunity.  Represents the price before any Sales or Marketing discounts are applied.</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Info__mdt/Payment_Plan_Info__mdt.object-meta.xml
<CustomObject>
    <description>Stored information regarding Number of Payments, Number of Fees and, for Hybrid, % of First Payment.</description>
    <label>Payment Plan Info</label>
    <pluralLabel>Payment Plan Info</pluralLabel>
</CustomObject>

force-app/main/default/objects/Payment_Plan_Info__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Onetime</fullName>
                <label>One-time</label>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
                <isActive>false</isActive>
                <label>Hybrid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Order_Builder_Visible__c.field-meta.xml
<CustomField>
    <fullName>Order_Builder_Visible__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This product is directly available in Order Builder.</description>
    <label>Order Builder Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Due_at_Checkout__c.field-meta.xml
<CustomField>
    <fullName>Due_at_Checkout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Some products are paid in full at checkout, such as Kit Fees, Shipping etc.</description>
    <inlineHelpText>Some products are paid in full at checkout, such as Kit Fees, Shipping etc.</inlineHelpText>
    <label>Due at Checkout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Eligible_for_Volume_Discounting__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Volume_Discounting__c</fullName>
    <defaultValue>false</defaultValue>
    <description>There is still a (possibly temporary) mode of discounting based on quantities of Biobanking products selected.  This flag indicates that this product should be included in that calculation and discounting.</description>
    <inlineHelpText>Indicates that this product is subject to automated discounting based on quantity.</inlineHelpText>
    <label>Eligible for Volume Discounting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Exempt_From_Discounts__c.field-meta.xml
<CustomField>
    <fullName>Exempt_From_Discounts__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this product will not have any discounts applied.</description>
    <inlineHelpText>Check this box for Products that should not allow any discounting to be applied.</inlineHelpText>
    <label>Exempt From Discounts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Is_Biobanking_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_Biobanking_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if this is a Biobanking product OR a bundle including Biobanking product(s)</description>
    <inlineHelpText>True if this is a Biobanking product OR a bundle including Biobanking product(s)</inlineHelpText>
    <label>Is Biobanking Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Partial_Amount_Due_At_Checkout__c.field-meta.xml
<CustomField>
    <fullName>Partial_Amount_Due_At_Checkout__c</fullName>
    <description>Enter an amount if this product should have some portion of its cost due at checkout.  This is distinct from the Due_at_Checkout__c field which indicates a Product&apos;s ENTIRE cost is due up front.</description>
    <label>Partial Amount Due At Checkout</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Relationship__c/Product_Relationship__c.object-meta.xml
<CustomObject>
    <description>Allows us to create relationships between products to define things such as suggested upsells or required add-ons.</description>
    <label>Product Relationship</label>
    <nameField>
        <displayFormat>PRN-{000000}</displayFormat>
        <label>Product Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Relationship__c/fields/Primary_Product__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary product in this relationship.</description>
    <label>Primary Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Related Products</relationshipLabel>
    <relationshipName>Related_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Relationship__c/fields/Related_Product__c.field-meta.xml
<CustomField>
    <fullName>Related_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The secondary product in this relationship</description>
    <label>Related Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Products</relationshipLabel>
    <relationshipName>Parent_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Relationship__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required Add-On</fullName>
            </value>
            <value>
                <fullName>Suggested Upsell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderBuilderController.cls
public with sharing class OrderBuilderController {

    @AuraEnabled(cacheable = true)
    public static string getSearchableItems(Id recordId){
        try {

            ID pricebookId;
            System.debug('recordId.getsobjecttype(): '+recordId.getsobjecttype());
            if (recordId.getsobjecttype()==Schema.Opportunity.getSObjectType()) {
                Opportunity opp = [SELECT ID, Pricebook2Id FROM Opportunity WHERE ID=:recordId];
                pricebookId = opp.Pricebook2Id;
                System.debug('pricebookId: '+pricebookId);
                System.debug('opp: '+JSON.serialize(opp));
            } else if (recordId.getsobjecttype()==Schema.fw1__Invoice__c.getSObjectType()) {
                fw1__Invoice__c invoice = [SELECT ID, Price_Book__c FROM fw1__Invoice__c WHERE ID=:recordId];
                pricebookId = invoice.Price_Book__c;
            }

            //Get bundle pricebook entries
            List < Bundle_Pricebook_Entry__c > bundlePricebookEntries = [SELECT ID, Bundle__c, Price_Book__c, List_Price__c FROM Bundle_Pricebook_Entry__c WHERE Order_Builder_Visible__c=true AND Price_Book__c=:pricebookId];

            System.debug('bpe query pb: '+pricebookId);

            System.debug('bundlePricebookEntries: '+bundlePricebookEntries);

            List < ID > bundleIds = new List < ID >();
            for (Bundle_Pricebook_Entry__c bpbe: bundlePricebookEntries) {
                bundleIds.add(bpbe.Bundle__c);
            }

            // Get bundles and bundle members 
            Map < ID, Bundle__c > availBundlesMap = new Map < ID, Bundle__c >([SELECT ID, Name, Description__c, Valid_From_Date__c, Valid_To_Date__c, Type__c, Storage_Type__c, (SELECT ID, Name, Bundle__c, Quantity__c, Product__c, Product__r.Name, Product__r.Exempt_From_Discounts__c, Product__r.Description, Product__r.Partial_Amount_Due_At_Checkout__c, Product__r.Due_at_Checkout__c, Product__r.Family, Product__r.Is_Biobanking_Product__c, Product__r.Eligible_for_Volume_Discounting__c,Product__r.ProductCode FROM Bundle_Members__r) FROM Bundle__c WHERE ID in:bundleIds]);

            System.debug('availBundlesMap: '+availBundlesMap);

            
            // Get PricebookEntries/Products
            List < PricebookEntry > availProducts = [SELECT ID, Product2Id, UnitPrice, Product2.Name, Product2.IsActive, Product2.Exempt_From_Discounts__c, Product2.Description, Product2.Partial_Amount_Due_At_Checkout__c, Product2.Due_at_Checkout__c, Order_Builder_Visible__c, Product2.Family, Product2.Is_Biobanking_Product__c, Product2.Eligible_for_Volume_Discounting__c, ProductCode FROM PricebookEntry WHERE IsActive=true AND Pricebook2Id=:pricebookId];

            System.debug('availProducts: '+availProducts);

            List < ID > productIds = new List < ID >();
            for (PricebookEntry pbe: availProducts) {
                productIds.add(pbe.Product2Id);
            }

            // Get all products including their related product relationships
            // TODO: validation rule that related products must be in same pricebook
            List < Product2 > productsWithRelated = [SELECT ID, Name, IsActive, Exempt_From_Discounts__c, Description, Partial_Amount_Due_At_Checkout__c, Due_at_Checkout__c, Family, Is_Biobanking_Product__c, Eligible_for_Volume_Discounting__c, (SELECT ID, Related_Product__c, Related_Product__r.Name, Relationship__c FROM Related_Products__r) FROM Product2 WHERE IsActive=true AND ID in:productIds];

            Map < ID, List < Product_Relationship__c >> productsWithRelatedMap = new Map < ID, List < Product_Relationship__c >>();
            for (Product2 prod: productsWithRelated) {
                if (prod.Related_Products__r.size()>0) {
                    productsWithRelatedMap.put(prod.Id, prod.Related_Products__r);
                }
            }

            // Populate class map of all list prices
            Map < ID, Decimal > productListPricesMap = new Map < ID, Decimal >();
            for (PricebookEntry pbEntry: availProducts) {
                productListPricesMap.put(pbEntry.Product2Id,pbEntry.UnitPrice);
            }

            // Get all Valid Discounts
            List < Discount__c > currentDiscounts = [SELECT ID, Amount__c, Bundle__c, Name, Marketing_Code__c, System_Applied__c, Services_Count__c,Applicable_Storage_Type__c, Method__c, Minimum_Order_Amount__c, Percentage__c, Product__c, Type__c, Valid_From__c, Valid_To__c, Active__c, Description__c FROM Discount__c WHERE Active__c=TRUE AND System_Applied__c=false];

            // Populate final searchable items collection
            List < Order.SearchableItem > allSearchableItems = new List < Order.SearchableItem >();

            for (Bundle_Pricebook_Entry__c bpbe: bundlePricebookEntries) {
                Bundle__c bundle = availBundlesMap.get(bpbe.Bundle__c);
                allSearchableItems.add(new Order.SearchableItem(bundle, bpbe, productListPricesMap, productsWithRelatedMap));
            }

            for (PricebookEntry pbe: availProducts) {
                if (pbe.Order_Builder_Visible__c) {
                    allSearchableItems.add(new Order.SearchableItem(pbe, productsWithRelatedMap));
                } 
            }

            for (Discount__c disc: currentDiscounts) {
                allSearchableItems.add(new Order.SearchableItem(disc));
            }
            

            return JSON.serialize(allSearchableItems);


        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    @AuraEnabled
    public static string loadOrder(Id orderId){
        try {
            Order thisOrder = new Order(orderId);
            return JSON.serialize(thisOrder);
        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    // TEMPORARY
    @AuraEnabled(cacheable = true)
    public static string getBiobankingDiscounts(){
        try {
            List < Discount__c > biobankingDiscounts = [SELECT ID, Amount__c, Bundle__c, Name, Marketing_Code__c, System_Applied__c, Method__c, Minimum_Order_Amount__c, Percentage__c, Product__c, Type__c, Valid_From__c, Valid_To__c, Active__c, Description__c, Services_Count__c, Applicable_Storage_Type__c FROM Discount__c WHERE Active__c=TRUE AND System_Applied__c=true];

            List < Discount > discountWrappers = new List < Discount >();
            for (Discount__c disc: biobankingDiscounts) {
                discountWrappers.add(new Discount(disc));
            }

            String responseJSON = '{"discountRecords":'+JSON.serialize(discountWrappers)+'}';
            return responseJSON;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable = true)
    public static string getAvailablePaymentOptions(){
        try {
            List < Payment_Plan_Info__mdt > payPlans = Payment_Plan_Info__mdt.getAll().values();
            List < PaymentPlan > payPlanOptions = new List < PaymentPlan > ();
            for (Payment_Plan_Info__mdt pp: payPlans ) {
                PaymentPlan ppWrapper = new PaymentPlan(pp);
                if (pp.Active__c==true) {
                    payPlanOptions.add(ppWrapper);
                }
            }
            return JSON.serialize(payPlanOptions);
        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    @AuraEnabled(cacheable = false)
    public static String addProducts(String orderJSON, String productJSON){

        try {
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            List < Product > products = (List < Product >) JSON.deserialize ( productJSON, List < Product >.class );
            order.addProducts(products);

            return JSON.serialize(order.productsOrdered);

        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    @AuraEnabled(cacheable = false)
    public static String addBundle(String orderJSON, String bundleJSON){
        try {
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            Bundle bundle = (Bundle) JSON.deserialize ( bundleJSON, Bundle.class );
            order.addBundle(bundle);

            return JSON.serialize(order);

        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    @AuraEnabled(cacheable = false)
    public static String addDiscount(String orderJSON, String discountJSON){
        try {
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            Discount discount = (Discount) JSON.deserialize ( discountJSON, Discount.class );
            order.addDiscount(discount);

            // return just the id of the discount added
            String appliedDiscountId;
            for (Discount disc:order.discountsOrdered) {
                if (disc.Id==discount.Id) {
                    appliedDiscountId = disc.appliedDiscountId;
                }
            }

            return appliedDiscountId;

        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    @AuraEnabled(cacheable = false)
    public static Void removeDiscount(String orderJSON, String discountJSON){
        try {
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            Discount discount = (Discount) JSON.deserialize ( discountJSON, Discount.class );
            order.removeDiscount(discount);
        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }



    @AuraEnabled(cacheable = false)
    public static void removeProduct(String orderJSON, String productId){
        try {
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            List < ID > productIdInList = new List < ID >{productId};
            order.removeProducts(productIdInList);

        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    @AuraEnabled(cacheable = false)
    public static String removeBundle(String orderJSON, String bundleId){
        try {
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            List < ID > bundleIdInList = new List < ID >{bundleId};
            order.removeBundles(bundleIdInList);
            return JSON.serialize(updatedOrderByContext(order));

        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    

    @AuraEnabled(cacheable = false)
    public static Boolean clearOrder(String orderJSON){
        try {
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            order.clearOrder();
            return true;
        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    @AuraEnabled(cacheable = false)
    public static String updateBundleQuantities(String orderJSON, String bundleJSON){
        try {
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            Bundle bundle = (Bundle) JSON.deserialize  (bundleJSON, Bundle.class) ;
            order.applyQuantityUpdates(bundle);
            return JSON.serialize(updatedOrderByContext(order));

        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    @AuraEnabled(cacheable = false)
    public static String updateProductQuantities(String orderJSON, String productJSON){
        try {
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            Product product = (Product) JSON.deserialize  (productJSON, Product.class) ;
            order.applyQuantityUpdates(product);
            return JSON.serialize(updatedOrderByContext(order));

        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    @AuraEnabled(cacheable = false)
    public static Void removePaymentPlan(String orderJSON){
        try {
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            order.removePaymentPlan();
        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    @AuraEnabled(cacheable = false)
    public static Void updatePaymentPlan(String orderJSON, String paymentJSON){
        try {
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            PaymentPlan pp = (PaymentPlan) JSON.deserialize  (paymentJSON, PaymentPlan.class) ;
            order.updatePaymentPlan(pp);
        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    @AuraEnabled(cacheable = false)
    public static Void updateAdditionToFirstPayment(String orderJSON, Decimal amount){
        try {
            if (amount==null) {
                amount = 0;
            }
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            order.updateAdditionToFirstPayment(amount);
        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    @AuraEnabled(cacheable = false)
    public static void removeBundlesAndProducts (String orderJSON, String products, String bundles){
        try {
            Order order = (Order) JSON.deserialize ( orderJSON, Order.class );
            List < ID > productIdList = (List < ID >) JSON.deserialize ( products, List < ID >.class );
            List < ID > bundleIdList = (List < ID >) JSON.deserialize ( bundles, List < ID >.class );

            if (productIdList.size()>0) {
                order.removeProducts(productIdList);
            }
            if (bundleIdList.size()>0) {
                order.removeBundles(bundleIdList);
            }
            
            

        } catch (Exception e) {
            throw new OrderBuilderException(e, 'OrderBuilderController');
        }
    }

    private static Order updatedOrderByContext(Order order) {
        Order updatedOrder;
        if (order.orderContext=='Opportunity') {
            updatedOrder = new Order(order.opportunityId);
        } else {
            updatedOrder = new Order(order.invoiceId);
        }
        return updatedOrder;
    }
}