force-app/main/default/objects/Bundle__c/Bundle__c.object-meta.xml
<CustomObject>
    <description>Represents a bundle of products that are marketed, priced and sold as a unit</description>
    <label>Bundle</label>
    <nameField>
        <label>Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Affects how bundles are shown and filtered in the Order Builder.</description>
    <inlineHelpText>Single-Product bundles contain storage + processing for one service.  Multi-Product bundles contain two or more services or products.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single-Product</fullName>
            </value>
            <value>
                <fullName>Multi-Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Dollar amount of the discount.</description>
    <inlineHelpText>The dollar amount of the discount. Only select if the Method is Amount.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Applicable_Storage_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Storage_Type__c</fullName>
    <description>When multi-biobanking discounts are sunsetted, this field may no longer be needed.</description>
    <inlineHelpText>For some system-applied discounts, the applicable storage type is relevant for picking the appropriate discount based on the number of services selected. Leave empty for other discount types.</inlineHelpText>
    <label>Applicable Storage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Storage_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The bundle that this discount is restricted to.</description>
    <label>Bundle</label>
    <referenceTo>Bundle__c</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Marketing_Code__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Code__c</fullName>
    <description>For marketing discounts that involve a code.</description>
    <inlineHelpText>If this discount is associated with a marketing code, enter it here.</inlineHelpText>
    <label>Marketing Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Is this a percentage discount or a fixed amount?</description>
    <inlineHelpText>Indicate if this is a flat-amount discount or a percentage. Only fill in the appropriate amount or percentage below.</inlineHelpText>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amount</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <description>The percentage of this discount</description>
    <inlineHelpText>The percentage of this discount.  Only enter if Method is Percentage.</inlineHelpText>
    <label>Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Product that this discount is restricted to.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Services_Count__c.field-meta.xml
<CustomField>
    <fullName>Services_Count__c</fullName>
    <description>When multi-biobanking discounts are sunsetted, this field may no longer be needed.</description>
    <inlineHelpText>For some system-applied discounts, the number of services is relevant for picking the appropriate discount based on the number of services selected.  Leave empty for other discount types</inlineHelpText>
    <label>Services Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/System_Applied__c.field-meta.xml
<CustomField>
    <fullName>System_Applied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Likely Temporary - Used for adding multi-biobanking services discounts that do not show up as findable in the builder.  Added via automation.  Once new pricing scheme is adopted, this field can be deprecated.</description>
    <inlineHelpText>Used for adding multi-biobanking services discounts that do not show up as findable in the builder</inlineHelpText>
    <label>System Applied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bundle Specific</fullName>
            </value>
            <value>
                <fullName>Product Specific</fullName>
            </value>
            <value>
                <fullName>Whole Order</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Multi-Annual Storage</fullName>
            </value>
            <value>
                <fullName>Multi-Biobanking Pkg</fullName>
            </value>
            <value>
                <fullName>Ad-Hoc Sales</fullName>
                <isActive>false</isActive>
                <label>Ad-Hoc Sales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_DiscountFactory.cls
@isTest
public class Test_DiscountFactory {
    private Discount__c current;

    public Test_DiscountFactory(Discount__c current) {
        this.current = current;
    }

     // Entry point builder method to start composing object attributes- default values for required fields- can be overridden
    public static Test_DiscountFactory start() {
        return new Test_DiscountFactory(
            new Discount__c (Name='Test Discount', Description__c='Test Discount Description')
        );
    }

    // Composable Functions
    public Test_DiscountFactory overrideName(String name) {
        current.Name = name;
        return this;
    }

    public Test_DiscountFactory amountBased(Decimal amount){
        current.Amount__c = amount;
        current.Method__c = 'Amount';
        return this;
    }

    public Test_DiscountFactory percentageBased(Decimal percentage){
        current.Percentage__c = percentage;
        current.Method__c = 'Percentage';
        return this;
    }

    public Test_DiscountFactory asSales() {
        current.Type__c = 'Sales';
        return this;
    }

    public Test_DiscountFactory withCode(String code) {
        current.Marketing_Code__c = code;
        return this;
    }

    public Test_DiscountFactory asBundleSpecific(ID bundleId) {
        current.Type__c = 'Bundle Specific';
        current.Bundle__c = bundleId;
        return this;
    }

    public Test_DiscountFactory asProductSpecific(ID productId) {
        current.Type__c = 'Product Specific';
        current.Product__c = productId;
        return this;
    }

    public Test_DiscountFactory asWholeOrder() {
        current.Type__c = 'Whole Order';
        return this;
    }

    public Test_DiscountFactory asSystemApplied() {
        current.System_Applied__c = true;
        return this;
    }

    public Test_DiscountFactory asMultiBiobanking(Integer count) {
        current.Services_Count__c = count;
        current.Type__c = 'Multi-Biobanking Pkg';
        current.System_Applied__c = true;
        return this;
    }

    public Test_DiscountFactory setApplicableStorageType(String storageType) {
        current.Applicable_Storage_Type__c = storageType;
        return this;
    }

    public Discount__c build() {
        return current;
    }

    public Discount__c create() {
        insert current;
        return current;
    }


}