force-app/main/default/objects/Bundle__c/Bundle__c.object-meta.xml
<CustomObject>
    <description>Represents a bundle of products that are marketed, priced and sold as a unit</description>
    <label>Bundle</label>
    <nameField>
        <label>Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Affects how bundles are shown and filtered in the Order Builder.</description>
    <inlineHelpText>Single-Product bundles contain storage + processing for one service.  Multi-Product bundles contain two or more services or products.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single-Product</fullName>
            </value>
            <value>
                <fullName>Multi-Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bundle__c/fields/Valid_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_From_Date__c</fullName>
    <label>Valid From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bundle__c/fields/Valid_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_To_Date__c</fullName>
    <label>Valid To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bundle_Member__c/Bundle_Member__c.object-meta.xml
<CustomObject>
    <description>Join object that relates Products to Bundles</description>
    <label>Bundle Member</label>
    <nameField>
        <displayFormat>BMN-{000000}</displayFormat>
        <label>Bundle Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Member__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <description>The bundle that this bundle-member applied to</description>
    <label>Bundle</label>
    <referenceTo>Bundle__c</referenceTo>
    <relationshipLabel>Bundle Members</relationshipLabel>
    <relationshipName>Bundle_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bundle_Member__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product that this bundle member adds. Ideally this would be required at the field level, but Product lookups cannot be made required -- SF limitation.</description>
    <inlineHelpText>Required!</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Members</relationshipLabel>
    <relationshipName>Bundle_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bundle_Member__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>How many of this line item are represented in the bundle.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/Bundle_Pricebook_Entry__c.object-meta.xml
<CustomObject>
    <label>Bundle Pricebook Entry</label>
    <nameField>
        <displayFormat>BPE-{000000}</displayFormat>
        <label>Pricebook Entry Bundle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Pricebook Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <label>Bundle</label>
    <referenceTo>Bundle__c</referenceTo>
    <relationshipLabel>Bundle Pricebook Entries</relationshipLabel>
    <relationshipName>Bundle_Pricebook_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>Marketing price for the bundle in this pricebook</description>
    <label>List Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/fields/Order_Builder_Visible__c.field-meta.xml
<CustomField>
    <fullName>Order_Builder_Visible__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This product is directly available in Order Builder.</description>
    <label>Order Builder Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Bundle Pricebook Entries</relationshipLabel>
    <relationshipName>Bundle_Pricebook_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_BundleFactory.cls
@isTest
public class Test_BundleFactory {
    private Bundle__c current;

    public Test_BundleFactory(Bundle__c current) {
        this.current = current;
    }

    public static Test_BundleFactory start() {
        return new Test_BundleFactory(
            new Bundle__c(Name='Test Bundle', Description__c='Test Bundle Description')
        );
    }

    public Test_BundleFactory overrideName(String name) {
        current.Name = name;
        return this;
    }

    public Test_BundleFactory asSingleProduct() {
        current.Type__c = 'Single-Product';
        return this;
    }

    public Test_BundleFactory asMultiProduct() {
        current.Type__c = 'Multi-Product';
        return this;
    }

    public Test_BundleFactory setTimeframe(Date startDate, Date endDate) {
        current.Valid_From_Date__c = startDate;
        current.Valid_To_Date__c = endDate;
        return this;
    }

    public Bundle__c create(Decimal amount) {
        insert current;

        Bundle_Pricebook_Entry__c bpe = new Bundle_Pricebook_Entry__c(
            Price_Book__c = Test.getStandardPricebookId(),
            Bundle__c = current.Id,
            List_Price__c = amount,
            Order_Builder_Visible__c = true
        );
        insert bpe;
        return current;
    }

    public Bundle__c createWithBundleMembers(List < Product2 > products, Decimal amount) {
        insert current;

        Bundle_Pricebook_Entry__c bpe = new Bundle_Pricebook_Entry__c(
            Price_Book__c = Test.getStandardPricebookId(),
            Bundle__c = current.Id,
            List_Price__c = amount,
            Order_Builder_Visible__c = true
        );
        insert bpe;
        System.debug('bpe: '+bpe);

        List < Bundle_Member__c > bundleMembers = new List < Bundle_Member__c > ();
        for (Product2 p: products) {
            Bundle_Member__c bm = new Bundle_Member__c();
            bm.Product__c = p.Id;
            bm.Bundle__c = current.Id;
            bm.Quantity__c = 1;
            bundleMembers.add(bm);
        }

        insert bundleMembers;
        return current;
    }

    public Bundle__c build() {
        return current;
    }
}