force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>This object will hold any errors that might occur within the Org.</description>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Apex Class where the log originated.</description>
    <label>Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A description of the log entry.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/HTTP_Response__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Response__c</fullName>
    <description>The HTTP Response received for the log entry.</description>
    <label>HTTP Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/HTTP_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Status_Code__c</fullName>
    <description>The HTTP Status Code received for the log entry.</description>
    <label>HTTP Status Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>Line number of the code where the log originated.</description>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>The method where the log originated.</description>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This is the log entry type.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LogHandlerTest.cls
/**
* @description Log Handler Test
* @author jseibert
* @since 2021
*/
@SuppressWarnings('PMD.MethodNamingConventions')
@isTest
public class LogHandlerTest {
    @isTest
    private static void validateLogHandler_Informational(){
        LogHandler.logInformation('LogHandlerTest', 'validateLogHandler_Informational', 'TEST');
        LIST<ERROR_LOG__C> lstLogEntries = [SELECT Class__c,Method__c,Description__c,Type__c FROM ERROR_LOG__C LIMIT 1];

        System.assertEquals('LogHandlerTest', lstLogEntries[0].Class__c, 'ERROR_LOG__C TEST FAILED - CLASS NOT MATCHING');

        System.assertEquals('validateLogHandler_Informational', lstLogEntries[0].Method__c, 'ERROR_LOG__C TEST FAILED - METHOD NOT MATCHING');

        System.assertEquals('TEST', lstLogEntries[0].Description__c, 'ERROR_LOG__C TEST FAILED - DESCRIPTION NOT MATCHING');

        System.assertEquals('Information', lstLogEntries[0].Type__c, 'ERROR_LOG__C TEST FAILED - TYPE NOT MATCHING');

    }

    @isTest
    private static void validateLogHandler_Success(){
        LogHandler.logSuccessData('LogHandlerTest', 'validateLogHandler_Informational', 'TEST');
        LIST<ERROR_LOG__C> lstLogEntries = [SELECT Class__c,Method__c,Description__c,Type__c FROM ERROR_LOG__C LIMIT 1];

        System.assertEquals('LogHandlerTest', lstLogEntries[0].Class__c, 'ERROR_LOG__C TEST FAILED - CLASS NOT MATCHING');

        System.assertEquals('validateLogHandler_Informational', lstLogEntries[0].Method__c, 'ERROR_LOG__C TEST FAILED - METHOD NOT MATCHING');

        System.assertEquals('TEST', lstLogEntries[0].Description__c, 'ERROR_LOG__C TEST FAILED - DESCRIPTION NOT MATCHING');

        System.assertEquals('Success', lstLogEntries[0].Type__c, 'ERROR_LOG__C TEST FAILED - TYPE NOT MATCHING');

    }    

    @isTest
    private static void validateLogHandler_Exception(){
        LogHandler.logException('LogHandlerTest', 'validateLogHandler_Informational', 'TEST',9999);
        LIST<ERROR_LOG__C> lstLogEntries = [SELECT Class__c,Method__c,Description__c,Type__c, Line_Number__c FROM ERROR_LOG__C LIMIT 1];

        System.assertEquals('LogHandlerTest', lstLogEntries[0].Class__c, 'ERROR_LOG__C TEST FAILED - CLASS NOT MATCHING');

        System.assertEquals('validateLogHandler_Informational', lstLogEntries[0].Method__c, 'ERROR_LOG__C TEST FAILED - METHOD NOT MATCHING');

        System.assertEquals('TEST', lstLogEntries[0].Description__c, 'ERROR_LOG__C TEST FAILED - DESCRIPTION NOT MATCHING');

        System.assertEquals(9999, lstLogEntries[0].Line_Number__c, 'ERROR_LOG__C TEST FAILED - LINE NUMBER NOT MATCHING');        

        System.assertEquals('Error', lstLogEntries[0].Type__c, 'ERROR_LOG__C TEST FAILED - TYPE NOT MATCHING');

    }       

    @isTest
    private static void validateLogHandler_HTTPResponse(){
        HttpResponse response = new HttpResponse();
        response.setBody('HTTPBODY');
        response.setStatusCode(9999);

        LogHandler.logHTTPResponse('LogHandlerTest', 'validateLogHandler_Informational', 'TEST',response);
        LIST<ERROR_LOG__C> lstLogEntries = [SELECT Class__c,Method__c,Description__c,Type__c, HTTP_Response__c,HTTP_Status_code__c FROM ERROR_LOG__C LIMIT 1];

        System.assertEquals('LogHandlerTest', lstLogEntries[0].Class__c, 'ERROR_LOG__C TEST FAILED - CLASS NOT MATCHING');

        System.assertEquals('validateLogHandler_Informational', lstLogEntries[0].Method__c, 'ERROR_LOG__C TEST FAILED - METHOD NOT MATCHING');

        System.assertEquals('TEST', lstLogEntries[0].Description__c, 'ERROR_LOG__C TEST FAILED - DESCRIPTION NOT MATCHING');

        System.assertEquals('HTTPBODY', lstLogEntries[0].HTTP_Response__c, 'ERROR_LOG__C TEST FAILED - RESPONSE NOT MATCHING');        

        System.assertEquals(9999, lstLogEntries[0].HTTP_Status_code__c, 'ERROR_LOG__C TEST FAILED - STATUS CODE NOT MATCHING');             

        System.assertEquals('Information', lstLogEntries[0].Type__c, 'ERROR_LOG__C TEST FAILED - TYPE NOT MATCHING');

    }     
}