force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>This object will hold any errors that might occur within the Org.</description>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Apex Class where the log originated.</description>
    <label>Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A description of the log entry.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/HTTP_Response__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Response__c</fullName>
    <description>The HTTP Response received for the log entry.</description>
    <label>HTTP Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/HTTP_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Status_Code__c</fullName>
    <description>The HTTP Status Code received for the log entry.</description>
    <label>HTTP Status Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>Line number of the code where the log originated.</description>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>The method where the log originated.</description>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This is the log entry type.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LogHandler.cls
/**
* @description Log Handler
* @author jseibert
* @since 2021
* Test Class - LogHandlerTest
*/
@SuppressWarnings('PMD.ApexCRUDViolation, PMD.ExcessiveParameterList, PMD.AvoidDebugStatements')
public without sharing class LogHandler
{

    /**
     * @description Save information log
     * @param className name of the class 
     * @param methodName name of the method
     * @param description description of the response 
    */
    public static void logInformation(String className, String methodName, String description){
        Error_Log__c log = new Error_Log__c();
        log.Class__c = className;
        log.Method__c = methodName;
        log.Description__c = description;
        log.Type__c = 'Information';
        Insert log;
    }
     
    /**
     * @description Save success log
     * @param className name of the class 
     * @param methodName name of the method
     * @param description description of the response 
    */
    public static void logSuccessData(String className, String methodName, String description){
        Error_Log__c log = new Error_Log__c();
        log.Class__c = className;
        log.Method__c = methodName;
        log.Description__c = description;
        log.Type__c = 'Success';
        Insert log;
    }
     
    /**
    * @description Save exception log
    * @param className name of the class 
    * @param methodName name of the method
    * @param description description of the response
    * @param lineNumber line where error occurred 
    */
    public static void logException(String className, String methodName, String description, Integer lineNumber){
        Error_Log__c log = new Error_Log__c();
        log.Class__c = className;
        log.Method__c = methodName;
        log.Description__c = description;
        log.Type__c = 'Error';
        log.Line_Number__c = lineNumber;
        Insert log;

        System.debug(LoggingLevel.WARN,'Exception Encocuntered. Investigate Error_Log__c for details. Class:'+className+' method:'+methodName+' line:'+lineNumber+' description:'+description);
    }
     
    /**
     * @description Save HTTP response log
     * @param className name of the class 
     * @param methodName name of the method
     * @param description description of the response
     * @param response response from callout
     */
    public static void logHTTPResponse(String className, String methodName, String description, HttpResponse response){
        Error_Log__c log = new Error_Log__c();
        log.Class__c = className;
        log.Method__c = methodName;
        log.Description__c = description;
        log.Type__c = 'Information';
        if(response != null){
            log.HTTP_Response__c = response.getBody();
            log.HTTP_Status_code__c = response.getStatusCode();         
        }
        Insert log;
    }     

}