force-app/main/default/objects/Applied_Discount__c/Applied_Discount__c.object-meta.xml
<CustomObject>
    <description>Join object between Discount and Opportunity</description>
    <label>Applied Discount</label>
    <nameField>
        <displayFormat>AD-{00000}</displayFormat>
        <label>Applied Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applied Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applied_Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The discounted amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applied_Discount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Applied Discounts</relationshipLabel>
    <relationshipName>Applied_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applied_Discount__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The invoice this discount is applied to.</description>
    <label>Invoice</label>
    <referenceTo>fw1__Invoice__c</referenceTo>
    <relationshipLabel>Applied Discounts</relationshipLabel>
    <relationshipName>Applied_Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applied_Discount__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The opportunity this discount is applied to.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applied Discounts</relationshipLabel>
    <relationshipName>Applied_Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applied_Discount__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <description>The percentage of the discount applied</description>
    <label>Percentage</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bundle__c/Bundle__c.object-meta.xml
<CustomObject>
    <description>Represents a bundle of products that are marketed, priced and sold as a unit</description>
    <label>Bundle</label>
    <nameField>
        <label>Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Affects how bundles are shown and filtered in the Order Builder.</description>
    <inlineHelpText>Single-Product bundles contain storage + processing for one service.  Multi-Product bundles contain two or more services or products.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single-Product</fullName>
            </value>
            <value>
                <fullName>Multi-Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Dollar amount of the discount.</description>
    <inlineHelpText>The dollar amount of the discount. Only select if the Method is Amount.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Applicable_Storage_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Storage_Type__c</fullName>
    <description>When multi-biobanking discounts are sunsetted, this field may no longer be needed.</description>
    <inlineHelpText>For some system-applied discounts, the applicable storage type is relevant for picking the appropriate discount based on the number of services selected. Leave empty for other discount types.</inlineHelpText>
    <label>Applicable Storage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Storage_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The bundle that this discount is restricted to.</description>
    <label>Bundle</label>
    <referenceTo>Bundle__c</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Marketing_Code__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Code__c</fullName>
    <description>For marketing discounts that involve a code.</description>
    <inlineHelpText>If this discount is associated with a marketing code, enter it here.</inlineHelpText>
    <label>Marketing Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Is this a percentage discount or a fixed amount?</description>
    <inlineHelpText>Indicate if this is a flat-amount discount or a percentage. Only fill in the appropriate amount or percentage below.</inlineHelpText>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amount</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <description>The percentage of this discount</description>
    <inlineHelpText>The percentage of this discount.  Only enter if Method is Percentage.</inlineHelpText>
    <label>Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Product that this discount is restricted to.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Services_Count__c.field-meta.xml
<CustomField>
    <fullName>Services_Count__c</fullName>
    <description>When multi-biobanking discounts are sunsetted, this field may no longer be needed.</description>
    <inlineHelpText>For some system-applied discounts, the number of services is relevant for picking the appropriate discount based on the number of services selected.  Leave empty for other discount types</inlineHelpText>
    <label>Services Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/System_Applied__c.field-meta.xml
<CustomField>
    <fullName>System_Applied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Likely Temporary - Used for adding multi-biobanking services discounts that do not show up as findable in the builder.  Added via automation.  Once new pricing scheme is adopted, this field can be deprecated.</description>
    <inlineHelpText>Used for adding multi-biobanking services discounts that do not show up as findable in the builder</inlineHelpText>
    <label>System Applied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bundle Specific</fullName>
            </value>
            <value>
                <fullName>Product Specific</fullName>
            </value>
            <value>
                <fullName>Whole Order</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Multi-Annual Storage</fullName>
            </value>
            <value>
                <fullName>Multi-Biobanking Pkg</fullName>
            </value>
            <value>
                <fullName>Ad-Hoc Sales</fullName>
                <isActive>false</isActive>
                <label>Ad-Hoc Sales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <description>Discount valid from date/time</description>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Valid_To__c.field-meta.xml
<CustomField>
    <fullName>Valid_To__c</fullName>
    <description>Valid until date/time</description>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Discount.cls
public with sharing class Discount {
    public Id Id;
    public Id appliedDiscountId;
    public ID opportunityId;
    public ID invoiceId;
    public Id productId;
    public Id bundleId;
    public String name;
    public String description;
    public String marketingCode;
    public String type; //bundle discount or product disocunt
    public String method; //percentage or amt
    public Datetime validFrom;
    public Datetime validTo;
    public Decimal amount;
    public Decimal amountAsNegative;
    public Decimal percentage;
    public Boolean systemApplied; //ideally temporary for multi-biobanking discounts
    public Integer ServicesCount; //ideally temporary for multi-biobanking discounts
    public String applicableStorageType; //ideally temporary for multi-biobanking discounts

    public Discount(){}

    public Discount(Discount__c disc) {
        this.Id = disc.Id;
        this.bundleId = disc.Bundle__c;
        this.productId = disc.Product__c;
        this.name = disc.Name;
        this.description = disc.Description__c;
        this.marketingCode = disc.Marketing_Code__c;
        this.type = disc.Type__c;
        this.method = disc.Method__c;
        this.validFrom = disc.Valid_From__c;
        this.validTo = disc.Valid_To__c;
        this.amount = disc.Amount__c;
        this.systemApplied = disc.System_Applied__c;
        this.ServicesCount = Integer.valueOf(disc.Services_Count__c);
        this.applicableStorageType = disc.Applicable_Storage_Type__c;
        if (this.amount>0) {
            this.amountAsNegative = this.amount * -1;
        }
        if (disc.Percentage__c>0) {
            this.percentage = disc.Percentage__c/100; //Salesforce stores percentage fields as whole numbers
        }
        
    }

    public Discount(Applied_Discount__c appliedDisc) {
        this.Id = appliedDisc.Discount__c;
        this.appliedDiscountId = appliedDisc.Id;
        this.productId = appliedDisc.Discount__r.Product__c;
        this.bundleId = appliedDisc.Discount__r.Bundle__c;
        this.opportunityId = appliedDisc.Opportunity__c;
        this.invoiceId = appliedDisc.Invoice__c;
        this.name = appliedDisc.Discount__r.Name;
        this.description = appliedDisc.Discount__r.Description__c;
        this.marketingCode = appliedDisc.Discount__r.Marketing_Code__c;
        this.type = appliedDisc.Discount__r.Type__c;
        this.method = appliedDisc.Discount__r.Method__c;
        this.validFrom = appliedDisc.Discount__r.Valid_From__c;
        this.validTo = appliedDisc.Discount__r.Valid_To__c;
        this.amount = appliedDisc.Amount__c;
        this.systemApplied = appliedDisc.Discount__r.System_Applied__c;
        this.ServicesCount = Integer.valueOf(appliedDisc.Discount__r.Services_Count__c);
        this.applicableStorageType = appliedDisc.Discount__r.Applicable_Storage_Type__c;
        if (this.amount>0) {
            this.amountAsNegative = this.amount * -1;
        }
        //For ad-hoc sales percentage discounts, the percentage is stored in the applied discount record, otherwise, the linked discount record
        if (appliedDisc.Percentage__c!=null && appliedDisc.Percentage__c>0) {
            this.percentage = appliedDisc.Percentage__c/100; //Salesforce stores percentage fields as whole numbers
        } else if (appliedDisc.Discount__r.Percentage__c>0) {
            this.percentage = appliedDisc.Discount__r.Percentage__c/100; //Salesforce stores percentage fields as whole numbers
        }
        
    }
}