force-app/main/default/objects/Baby__c/Baby__c.object-meta.xml
<CustomObject>
    <label>Family Member</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Baby__c/fields/Baby_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Baby_First_Name__c</fullName>
    <formula>IF (
OR (
CONTAINS(Name_of_Child__c, &quot;Baby&quot;),
CONTAINS(Name_of_Child__c, &quot;Twin&quot;),
CONTAINS(Name_of_Child__c, &quot;UNA&quot;),
CONTAINS(Name_of_Child__c, &quot;Unknown&quot;),
CONTAINS(Name_of_Child__c, &quot;Female&quot;),
ISBLANK(Name_of_Child__c)),
null,
LEFT( Name_of_Child__c  ,FIND(&quot; &quot;, Name_of_Child__c,1)-1))</formula>
    <inlineHelpText>Returns only the first name upto the first space in the full name of child field.</inlineHelpText>
    <label>Baby First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>Collection_Date__c</fullName>
    <inlineHelpText>From the DCS</inlineHelpText>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/ISBT_My_Genome__c.field-meta.xml
<CustomField>
    <fullName>ISBT_My_Genome__c</fullName>
    <description>This is the ISBT for My Genome sample.</description>
    <inlineHelpText>This is the ISBT for My Genome sample.</inlineHelpText>
    <label>ISBT My Genome</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/ISBT_My_Newborn__c.field-meta.xml
<CustomField>
    <fullName>ISBT_My_Newborn__c</fullName>
    <description>This is the ISBT for My Newborn.</description>
    <inlineHelpText>This is the ISBT for My Newborn.</inlineHelpText>
    <label>ISBT My Newborn</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/Lab__c.field-meta.xml
<CustomField>
    <fullName>Lab__c</fullName>
    <label>Lab</label>
    <referenceTo>Lab__c</referenceTo>
    <relationshipName>Baby</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Baby__c/fields/LPI_My_Genome__c.field-meta.xml
<CustomField>
    <fullName>LPI_My_Genome__c</fullName>
    <description>This is the kit id for the My Genome sample.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the kit id for the My Genome sample.</inlineHelpText>
    <label>LPI My Genome</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Baby__c/fields/LPI_My_Newborn__c.field-meta.xml
<CustomField>
    <fullName>LPI_My_Newborn__c</fullName>
    <description>This is the kit id for the My Newborn sample.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the kit id for the My Newborn sample.</inlineHelpText>
    <label>Newborn Client ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Baby__c/fields/Mother_s_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_First_Name__c</fullName>
    <formula>Lab__r.Mother_s_First_Name__c</formula>
    <label>Mother&apos;s First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/Mother_s_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_Last_Name__c</fullName>
    <description>LU field from the Lab page, used for Genomics Permissions letter.</description>
    <formula>Lab__r.Mother_s_Last_Name__c</formula>
    <label>Mother&apos;s Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/My_Genome_Consent_URL__c.field-meta.xml
<CustomField>
    <fullName>My_Genome_Consent_URL__c</fullName>
    <description>This field contains the URL to the My Genome consent/surveys. This field is populated from the response from sending the data for processing.</description>
    <inlineHelpText>This field contains the URL to the My Genome consent/surveys. This field is populated from the response from sending the data for processing.</inlineHelpText>
    <label>My Genome Consent URL</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/My_Genome_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>My_Genome_Order_Status__c</fullName>
    <description>This is the status of the My Genome order from Veritas.</description>
    <inlineHelpText>Sent To Veritas = Order sent to Veritas.
Lab Info Sent To Veritas = Sample info sent to Veritas.
Sent Customer Consent Email = Order sent, consent email sent to patient.
New Order = Order created on Veritas Genetics, account created, email info is sent to patient.
Registered = Sample id assigned to order with sample type, collection date.
Received = Sample received in lab and passed Lab QC.
Distributed = Report generated and available for patient, email sent to patient.</inlineHelpText>
    <label>My Genome Order Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/My_Newborn_Consent_URL__c.field-meta.xml
<CustomField>
    <fullName>My_Newborn_Consent_URL__c</fullName>
    <description>This field contains the URL to the My Newborn consent/surveys. This field is populated from the response from sending the data for processing.</description>
    <inlineHelpText>This field contains the URL to the My Newborn consent/surveys. This field is populated from the response from sending the data for processing.</inlineHelpText>
    <label>My Newborn Consent URL</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/My_Newborn_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>My_Newborn_Order_Status__c</fullName>
    <description>This is the status of the My Newborn order from Veritas.</description>
    <inlineHelpText>Sent To Veritas = Order sent to Veritas.
Lab Info Sent To Veritas = Sample info sent to Veritas.
Sent Customer Consent Email = Order sent, consent email sent to patient.
New Order = Order created on Veritas Genetics, account created, email info is sent to patient.
Registered = Sample id assigned to order with sample type, collection date.
Received = Sample received in lab and passed Lab QC.
Distributed = Report generated and available for patient, email sent to patient.</inlineHelpText>
    <label>My Newborn Order Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/Sex_of_Child__c.field-meta.xml
<CustomField>
    <fullName>Sex_of_Child__c</fullName>
    <label>Sex of Child</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Non-Binary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab__c/Lab__c.object-meta.xml
<CustomObject>
    <label>Lab</label>
    <nameField>
        <label>Lab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Labs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab__c/fields/Birth_Date_from_Courier__c.field-meta.xml
<CustomField>
    <fullName>Birth_Date_from_Courier__c</fullName>
    <inlineHelpText>Provided via call center or digital courier pick-up</inlineHelpText>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>Collection_Date__c</fullName>
    <description>Date that the cord blood was collected by the doctor. This may be found on the Data Collection Sheet or the email from the courier.</description>
    <inlineHelpText>Date that the cord blood was collected by the doctor. This may be found on the Data Collection Sheet or the email from the courier.</inlineHelpText>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Cord_Blood_Order__c.field-meta.xml
<CustomField>
    <fullName>Cord_Blood_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cord Blood Order</label>
    <referenceTo>fw1__Invoice__c</referenceTo>
    <relationshipLabel>Labs</relationshipLabel>
    <relationshipName>Labs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Mother_s_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_First_Name__c</fullName>
    <inlineHelpText>Syncs with Contact info using a trigger</inlineHelpText>
    <label>Contact First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Mother_s_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_Last_Name__c</fullName>
    <inlineHelpText>Syncs with Contact info using a trigger</inlineHelpText>
    <label>Contact Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Mother_s_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_Phone__c</fullName>
    <inlineHelpText>Syncs with Contact info using a trigger</inlineHelpText>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Mothers_Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Mothers_Date_Of_Birth__c</fullName>
    <label>Contact Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Mothers_Email__c.field-meta.xml
<CustomField>
    <fullName>Mothers_Email__c</fullName>
    <inlineHelpText>Syncs with Contact info using a trigger</inlineHelpText>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>Shipping City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <defaultValue>&quot;US&quot;</defaultValue>
    <label>Shipping Country old</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_State_new__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State_new__c</fullName>
    <label>Shipping State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_Street__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Street__c</fullName>
    <label>Shipping Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_Zip__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Zip__c</fullName>
    <label>Shipping Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenomeOrderOutbound.cls
/**
* GenomeOrderOutbound
* ------------------
* @author jseibert
*/
public with sharing class GenomeOrderOutbound {
    public class GenomeOrderCalloutException extends Exception{}

    static final String SENT_TO_VERITAS = 'Sent To Veritas';
    static final String LAB_SENT_TO_VERITAS = 'Lab Info Sent To Veritas';
    static final String EMAIL_SENT_TO_CUSTOMER = 'Sent Customer Consent Email';
    static final String ERROR_SENDING_TO_VERITAS = 'Error: Order Callout Failed. Examine logs.';
    static final String VERITAS_NEW_ORDER = 'New Order';

    static final List<String> lstStatusOKToSendSample = new List<String>{EMAIL_SENT_TO_CUSTOMER,
                                                                        ERROR_SENDING_TO_VERITAS,
                                                                        SENT_TO_VERITAS,
                                                                        VERITAS_NEW_ORDER};
  

    /**
    * sendGenomeOrderWithBabyIds
    * -------
    * @param lstGenomeBabyRecords List of a List of Baby Ids to Proecss
    */
    @InvocableMethod(label='sendGenomeOrderWithBabyIds' description='This method will send the Genome Order for Processing Using the Baby Ids')
    public static void sendGenomeOrderWithBabyIds(List<List<String>> lstGenomeBabyRecords){
        List<String> lstBabyIds = new List<String>();
        List<Baby__c> lstBabyRecordsToProcess = new List<Baby__c>();

        /// get Baby Id List
        for(List<String> lstIds :  lstGenomeBabyRecords){
            lstBabyIds.addAll(lstIds);
        }

        System.debug('List of Baby Ids to Process:'+lstBabyIds);

        // query baby recs
        lstBabyRecordsToProcess = [
            SELECT 
            Id, Name, LPI_My_Genome__c, My_Genome_Order_Status__c, LPI_My_Newborn__c,My_Newborn_Order_Status__c,
            ISBT_My_Genome__c, ISBT_My_Newborn__c
            FROM Baby__c WHERE Id in :lstBabyIds
        ];

        // Loop For Each Baby and Send To Veritas
        for(Baby__c babyRec: lstBabyRecordsToProcess){         

            System.debug('lpimg:'+babyRec.LPI_My_Genome__c+'mgstatus:'+babyRec.My_Genome_Order_Status__c+'lpmn:'+babyRec.LPI_My_Newborn__c+'mnstatus:'+babyRec.My_Newborn_Order_Status__c);
            
            if (babyRec.LPI_My_Genome__c != null && 
                (babyRec.My_Genome_Order_Status__c == null || babyRec.My_Genome_Order_Status__c == ERROR_SENDING_TO_VERITAS) && 
                (babyRec.LPI_My_Newborn__c == null || 
                (babyRec.My_Newborn_Order_Status__c == LAB_SENT_TO_VERITAS || 
                babyRec.My_Newborn_Order_Status__c == EMAIL_SENT_TO_CUSTOMER))){ // mygenome set - initial order                                   
                sendOrder(babyRec.Id, 'MYGENOME',SENT_TO_VERITAS);
            }
            else if (babyRec.LPI_My_Newborn__c != null && 
                    (babyRec.My_Newborn_Order_Status__c == null || babyRec.My_Newborn_Order_Status__c == ERROR_SENDING_TO_VERITAS) && 
                    (babyRec.LPI_My_Genome__c == null || 
                    (babyRec.My_Genome_Order_Status__c == LAB_SENT_TO_VERITAS || 
                    babyRec.My_Genome_Order_Status__c == EMAIL_SENT_TO_CUSTOMER))){ // mynewborn set - intial order
                    sendOrder(babyRec.Id, 'MYNEWBORN',SENT_TO_VERITAS);

            }
            else if (babyRec.LPI_My_Newborn__c != null && 
                    (babyRec.My_Newborn_Order_Status__c == null || babyRec.My_Newborn_Order_Status__c == ERROR_SENDING_TO_VERITAS) && 
                    babyRec.LPI_My_Genome__c != null && 
                    (babyRec.My_Genome_Order_Status__c == null || babyRec.My_Genome_Order_Status__c == ERROR_SENDING_TO_VERITAS)){ // both set - initial order
                    sendOrder(babyRec.Id, 'MYGENOME',SENT_TO_VERITAS);
                    sendOrder(babyRec.Id, 'MYNEWBORN',SENT_TO_VERITAS);                
            }
            else if (babyRec.ISBT_My_Genome__c != null &&  lstStatusOKToSendSample.contains(babyRec.My_Genome_Order_Status__c) &&
                    (babyRec.ISBT_My_Newborn__c == null || babyRec.My_Newborn_Order_Status__c == LAB_SENT_TO_VERITAS)){ // mygenome ISBT set - order update
                        sendOrder(babyRec.Id, 'MYGENOME',LAB_SENT_TO_VERITAS);
             
            }
            else if (babyRec.ISBT_My_Newborn__c != null && lstStatusOKToSendSample.contains(babyRec.My_Newborn_Order_Status__c) && 
                    (babyRec.ISBT_My_Genome__c == null || babyRec.My_Genome_Order_Status__c == LAB_SENT_TO_VERITAS)){ // mynewborn ISBT set - order update
                        sendOrder(babyRec.Id, 'MYNEWBORN',LAB_SENT_TO_VERITAS);

            }    
            else if (babyRec.ISBT_My_Genome__c != null && lstStatusOKToSendSample.contains(babyRec.My_Newborn_Order_Status__c) && 
                    babyRec.ISBT_My_Newborn__c != null && lstStatusOKToSendSample.contains(babyRec.My_Genome_Order_Status__c)){ // both set - order update                        
                        sendOrder(babyRec.Id, 'MYGENOME',LAB_SENT_TO_VERITAS);
                        sendOrder(babyRec.Id, 'MYNEWBORN',LAB_SENT_TO_VERITAS);
            }    
                          

        }
            
    }

    /**
    * sendOrder
    * -------
    * @param babyRecord Baby record to send to Veritas
    * @param strOrderType Order type - MyGenome or MyNewborn
    */
    @future(Callout=true)
    private static void sendOrder(Id idBaby,String strOrderType,String strStatus){
        Boolean boolExceptionEncountered = false;
        String strOrderLevel;

        Baby__c babyRecord = [
            SELECT 
            Id, Name, LPI_My_Genome__c, My_Genome_Order_Status__c, LPI_My_Newborn__c,My_Newborn_Order_Status__c,
            ISBT_My_Genome__c, ISBT_My_Newborn__c,
            Baby_First_Name__c, Mother_s_First_Name__c, Mother_s_Last_Name__c,lab__r.Mother_s_Phone__c,
            lab__r.Shipping_Street__c,  lab__r.Shipping_City__c, lab__r.Shipping_State_new__c, lab__r.Shipping_Zip__c, lab__r.Shipping_Country__c,
            lab__r.Birth_Date_from_Courier__c,lab__r.Mothers_Date_Of_Birth__c,Collection_Date__c,
            Sex_of_Child__c,lab__r.Mothers_Email__c,
            lab__r.Cord_Blood_Order__r.My_Genome_Premium_Ordered__c, lab__r.Cord_Blood_Order__r.My_Genome_Standard_Ordered__c, 
            lab__r.Cord_Blood_Order__r.Newborn_Panel_Ordered__c,lab__r.Cord_Blood_Order__r.fw1__Invoice_Date__c
            FROM Baby__c WHERE Id = :idBaby        
        ];
        
        String strAuthToken = getAuthToken(strOrderType);

        HttpRequest req = new HttpRequest();

        // set endpoint depending on product and state
        if(strOrderType == 'MYGENOME' && babyRecord.ISBT_My_Genome__c != null){
            req.setEndpoint('callout:VeritasGenomeOrder/update_sample'); //TODO Get New Endpoint
        }
        else if(strOrderType == 'MYGENOME' && babyRecord.ISBT_My_Genome__c == null){
            req.setEndpoint('callout:VeritasGenomeOrder/order_create');
        }
        else if(strOrderType == 'MYNEWBORN' && babyRecord.ISBT_My_Newborn__c == null){
            req.setEndpoint('callout:VeritasNewbornOrder/order_create');
        }
        else if(strOrderType == 'MYNEWBORN' && babyRecord.ISBT_My_Newborn__c != null){
            req.setEndpoint('callout:VeritasNewbornOrder/order_create'); // this will be updated to update endpoing
        }

        if(strOrderType == 'MYGENOME' && babyRecord.Lab__r.Cord_Blood_Order__r.My_Genome_Premium_Ordered__c > 0){
            strOrderLevel = 'PREMIUM';
        }
        else if (strOrderType == 'MYGENOME' && babyRecord.Lab__r.Cord_Blood_Order__r.My_Genome_Standard_Ordered__c > 0){
            strOrderLevel = 'STANDARD';
        }
        else if (strOrderType == 'MYNEWBORN' && babyRecord.Lab__r.Cord_Blood_Order__r.Newborn_Panel_Ordered__c > 0){
            strOrderLevel = 'PANEL';
        }        
        
        System.debug('Endpoint:'+req.getEndpoint());
    
        req.setMethod('POST');
        req.setTimeout(30000); //30 seconds        
        req.setHeader('Authorization', 'Bearer '+ strAuthToken);
        req.setHeader('Content-Type', 'application/json');
    


        String strRequestBody = GenomeOrderHelper.constructGenomeOrder(babyRecord,strOrderType,strOrderLevel);
        req.setBody(strRequestBody);
    
        Http http = new Http();
        HttpResponse resp = new HttpResponse();
        String strException;
            
        try {
            resp = http.send(req);        
        }
        catch (Exception ex) {
            strException = ex.getMessage();
        }
        System.debug('response:'+resp.getBody());
        if((resp.getStatusCode() != 200 && resp.getStatusCode() != 201) || resp.getBody().contains('"statusCode": 400')){
            LogHandler.logHTTPResponse('GenomeOrderOutbound', 'sendOrder', 'Callout Failed. Examine Logs'+strException, resp);
            updateGenomeOrderValueSent(babyRecord, strOrderType, 'Error: Order Callout Failed. Examine logs.',null);
            }   
        else {
            if(strStatus == SENT_TO_VERITAS){
            String strSignupURL = GenomeOrderHelper.getSignupURLFromResponse(resp.getBody());
            updateGenomeOrderValueSent(babyRecord, strOrderType ,strStatus,strSignupURL);             
            }
            else if(strStatus == LAB_SENT_TO_VERITAS){
                updateGenomeOrderValueSent(babyRecord, strOrderType ,strStatus,null);             
            }
        }


    }


    /**
    * updateGenomeOrderValueSent
    * -------
    * @param babyRecordToUpdate Baby record that will have its status updated.
    * @param strOrderType Order type - MyGenome, MyNewborn 
    */
    public static void updateGenomeOrderValueSent(Baby__c babyRecordToUpdate, String strOrderType, String strStatus, String strSignupURL){
        if(strOrderType == 'MYGENOME'){
            babyRecordToUpdate.My_Genome_Order_Status__c = strStatus;
            if (strSignupURL != null){
                babyRecordToUpdate.My_Genome_Consent_URL__c = strSignupURL;
            }            
        }
        else if( strOrderType == 'MYNEWBORN'){
            babyRecordToUpdate.My_Newborn_Order_Status__c = strStatus;
            if (strSignupURL != null){
                babyRecordToUpdate.My_Newborn_Consent_URL__c = strSignupURL;
            }
        }

        try{
            update babyRecordToUpdate;
        }
        catch(Exception ex){
            LogHandler.logException('GenomeOrderOutbound', 'updateGenomeOrderValueSent', 'Update Baby Record Failed. Examine Logs'+ex.getMessage(),null);        
        }

        
    }

    /**
    * getAuthToken
    * -------
    * @return strAuthToken String of the Authentication Token
    */
    private static String getAuthToken(String strOrderType){
        String strAuthToken;
        String strBody;

        HttpRequest req = new HttpRequest();

        if(strOrderType == 'MYGENOME'){
            req.setEndpoint('callout:VeritasAuth/oauth2/token');
        }
        else if (strOrderType == 'MYNEWBORN'){
            req.setEndpoint('callout:VeritasAuthEU/oauth2/token');
        }

        req.setMethod('POST');
        strBody = 'grant_type=client_credentials';
        strBody +='&client_id={!$Credential.UserName}';
        strBody += '&client_secret={!$Credential.Password}'; 
        req.setBody(strBody);

        System.debug('reqbody:'+strBody);

        HttpResponse resp = new HttpResponse();
        Http h = new Http();
        resp = h.send(req);

        // Parse the JSON response
        if (resp.getStatusCode() != 201 && resp.getStatusCode() != 200) {            
            System.debug('Auth callout failed. Status code:'+resp.getStatusCode()+' status:'+resp.getStatus()); // will log above
        } else {
            map<string,Object> resultMap = (map<string,Object>)JSON.deserializeUntyped(resp.getBody());
            strAuthToken = (String)resultMap.get('access_token');         
        }

        return strAuthToken;
    }    

}