force-app/main/default/objects/Americord_Settings__c/Americord_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Americord Settings</label>
</CustomObject>

force-app/main/default/objects/Americord_Settings__c/fields/Ambassador_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Ambassador_Account_ID__c</fullName>
    <label>Ambassador Account ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Settings__c/fields/Current_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Current_Price_Book__c</fullName>
    <label>Current Price Book</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Settings__c/fields/Deposit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Amount__c</fullName>
    <label>Deposit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lab__c/Lab__c.object-meta.xml
<CustomObject>
    <label>Lab</label>
    <nameField>
        <label>Lab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Labs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Labs</relationshipLabel>
    <relationshipName>Labs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Cord_Blood_2_0_Stored__c.field-meta.xml
<CustomField>
    <fullName>Cord_Blood_2_0_Stored__c</fullName>
    <label>Cord Blood 2.0 Stored</label>
    <summaryFilterItems>
        <field>Baby__c.Cord_Blood_Cryogenically_Preserved__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Baby__c.Lab__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Number_of_Births__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Births__c</fullName>
    <formula>text( Cord_Blood_Order__r.Number_of_Births__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Births</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Relation_to_Baby__c.field-meta.xml
<CustomField>
    <fullName>Relation_to_Baby__c</fullName>
    <label>Contact Relation to Baby</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>Shipping City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <defaultValue>&quot;US&quot;</defaultValue>
    <label>Shipping Country old</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_Street__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Street__c</fullName>
    <label>Shipping Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_Zip__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Zip__c</fullName>
    <label>Shipping Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Authorized_Payment__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Populated by Process Builder, when Authorization is successful.</inlineHelpText>
    <label>Authorized Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cord_Blood_2_0__c.field-meta.xml
<CustomField>
    <fullName>Cord_Blood_2_0__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ZDeprecate Cord Blood 2.0</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cord_Tissue__c.field-meta.xml
<CustomField>
    <fullName>Cord_Tissue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ZDeprecate Cord Tissue</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Number_of_Births__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Births__c</fullName>
    <label>Number of Births</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Twins</fullName>
            </value>
            <value>
                <fullName>Triplets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Plans__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plans__c</fullName>
    <label>ZDEPRECATE_Payment Plans</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTP</fullName>
                <label>One-time Payment</label>
            </value>
            <value>
                <fullName>24M</fullName>
                <label>24 Months</label>
            </value>
            <value>
                <fullName>36M</fullName>
                <label>36 Months</label>
            </value>
            <value>
                <fullName>48M</fullName>
                <label>48 Months</label>
            </value>
            <value>
                <fullName>HY18</fullName>
                <label>Hybrid - 18</label>
            </value>
            <value>
                <fullName>12M</fullName>
                <label>12 Months</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Placenta_2_0__c.field-meta.xml
<CustomField>
    <fullName>Placenta_2_0__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ZDeprecate Placenta 2.0 (Amnion)</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_by_email_address__c.field-meta.xml
<CustomField>
    <fullName>Referred_by_email_address__c</fullName>
    <inlineHelpText>Provide the email address for the person who referred this client.</inlineHelpText>
    <label>Referred by email address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_by_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Referred_by_First_Name__c</fullName>
    <label>Referred by First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_by_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Referred_by_Last_Name__c</fullName>
    <label>Referred by Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Relation_to_Baby__c.field-meta.xml
<CustomField>
    <fullName>Relation_to_Baby__c</fullName>
    <label>Relation to Baby</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>US</label>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State_Province__c</fullName>
    <label>State / Province</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Street__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Street__c</fullName>
    <label>Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Zip__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Zip__c</fullName>
    <label>Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Storage_Plan__c.field-meta.xml
<CustomField>
    <fullName>Storage_Plan__c</fullName>
    <label>Storage Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Storage</fullName>
            </value>
            <value>
                <fullName>20YPP</fullName>
                <label>20 Years Prepaid</label>
            </value>
            <value>
                <fullName>ASP</fullName>
                <label>Annual Storage</label>
            </value>
            <value>
                <fullName>LTS</fullName>
                <label>Lifetime Storage</label>
            </value>
            <value>
                <fullName>Donated</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Is_Biobanking_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_Biobanking_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if this is a Biobanking product OR a bundle including Biobanking product(s)</description>
    <inlineHelpText>True if this is a Biobanking product OR a bundle including Biobanking product(s)</inlineHelpText>
    <label>Is Biobanking Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Is_Genomics_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_Genomics_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if this is a genomics product OR a bundle containing a genomics product.</description>
    <inlineHelpText>True if this is a genomics product OR a bundle containing a genomics product.</inlineHelpText>
    <label>Is Genomics Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AmericordTestDataFactory.cls
// Test Data Factory for Americord customizations

public class AmericordTestDataFactory {
    
    // base data
    public AmericordTestDataFactory () {

        // Setup PriceBooks
        Id standardPriceBookId = Test.getStandardPricebookId();
        Pricebook2 customPriceBook = new Pricebook2 (Name = 'Test 2020', 
                                                     Description = 'Test', 
                                                     IsActive = true );
        insert customPriceBook;
        Id customPriceBookId = customPriceBook.Id;

        // Create Products
        List < Product2 > productsForInsert = new List < Product2 > ();
       	Product2 prod = new Product2 (Name = 'Cord Blood 2.0', 
                                      IsActive = true, 
                                      ProductCode='CB',
                                      Family = 'Product',
                                      Is_Biobanking_Product__c=true);
        productsForInsert.add ( prod );

       	prod = new Product2 (Name = 'Cord Tissue', 
                                      IsActive = true, 
                                      ProductCode='CT',
                                      Family = 'Product',
                                      Is_Biobanking_Product__c=true);
        productsForInsert.add ( prod );

       	prod = new Product2 (Name = 'Placenta Tissue', 
                                      IsActive = true, 
                                      ProductCode='PT',
                                      Family = 'Product',
                                      Is_Biobanking_Product__c=true);
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Cord Blood + Cord Tissue', 
                             		IsActive = true, 
                                	ProductCode='CBCT',
                                	Family = 'Product',
                                    Is_Biobanking_Product__c=true);
        productsForInsert.add ( prod );
        
        prod = new Product2 (Name = 'Cord Blood + Cord Tissue + Placenta', 
                                	IsActive = true, 
                                	ProductCode='CBCTP',
                                	Family = 'Product',
                                    Is_Biobanking_Product__c=true);
        
        productsForInsert.add ( prod );
        
        prod = new Product2 (Name = 'Cord Blood 20yr Storage', 
                                	IsActive = true, 
                                	ProductCode='CB20Yr',
                                	Family = 'Storage');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Cord Tissue 20yr Storage', 
                                	IsActive = true, 
                                	ProductCode='CT20Yr',
                                	Family = 'Storage');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Cord Tissue Lifetime Storage', 
                                	IsActive = true, 
                                	ProductCode='CTLifetime',
                                	Family = 'Storage');
        productsForInsert.add ( prod );
        
        prod = new Product2 (Name = 'Cord Blood + Cord Tissue 20yr Storage', 
                                	IsActive = true, 
                                	ProductCode='CBCT20Yr',
                                	Family = 'Storage');
        productsForInsert.add ( prod );
        
        prod = new Product2 (Name = 'Cord Blood + Cord Tissue + Placenta 20yr Storage', 
                                	IsActive = true, 
                                	ProductCode='CBCTP20Yr',
                                	Family = 'Storage');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Cord Blood Lifetime Storage', 
                                	IsActive = true, 
                                	ProductCode='CBLifetime',
                                	Family = 'Storage');
        productsForInsert.add ( prod );
        
        prod = new Product2 (Name = 'Cord Blood + Cord Tissue Lifetime Storage', 
                                	IsActive = true, 
                                	ProductCode='CBCTLifetime',
                                	Family = 'Storage');
        productsForInsert.add ( prod );
        
        prod = new Product2 (Name = 'Cord Blood + Cord Tissue + Placenta Lifetime Storage', 
                                	IsActive = true, 
                                	ProductCode='CBCTPLifetime',
                                	Family = 'Storage');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Rush Shipping', 
                                	IsActive = true, 
                                	ProductCode='RushShip',
                                	Family = 'Shipping');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Standard Shipping', 
                                	IsActive = true, 
                                	ProductCode='StndShip',
                                	Family = 'Shipping');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Stem Cell Collection Kit', 
                                	IsActive = true, 
                                	ProductCode='CollKit');
        productsForInsert.add ( prod );
        
        prod = new Product2 (Name = 'Cord Blood + Cord Tissue + Placenta + Exosomes', 
                                	IsActive = true, 
                                	ProductCode='CBCTPEX',
                                    Family = 'Product',
                                    Is_Biobanking_Product__c=true);
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Cord Blood + Cord Tissue + Placenta + Exosomes + M&M', 
                                	IsActive = true, 
                                	ProductCode='CBCTPEXMM',
                                    Family = 'Product',
                                    Is_Biobanking_Product__c=true,
                                    Is_Genomics_Product__c=true);
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Cord Blood + Cord Tissue + Placenta + Exosomes + M&M 20yr Storage', 
                                	IsActive = true, 
                                	ProductCode='CBCTPEXMM20Yr',
                                	Family = 'Storage');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Cord Blood + Cord Tissue + Placenta + Exosomes + M&M Lifetime Storage', 
                                	IsActive = true, 
                                	ProductCode='CBCTPEXMMLifetime',
                                	Family = 'Storage');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Cord Blood + Cord Tissue + Placenta + Exosomes 20yr Storage', 
                                	IsActive = true, 
                                	ProductCode='CBCTPEX20Yr',
                                	Family = 'Storage');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Cord Blood + Cord Tissue + Placenta + Exosomes Lifetime Storage', 
                                	IsActive = true, 
                                	ProductCode='CBCTPEXLifetime',
                                	Family = 'Storage');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Exosomes', 
                                	IsActive = true, 
                                	ProductCode='EX',
                                	Family = 'Product',
                                    Is_Biobanking_Product__c=true);
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Exosomes 20yr Storage', 
                                	IsActive = true, 
                                	ProductCode='EX20Yr',
                                	Family = 'Storage');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Exosomes Lifetime Storage', 
                                	IsActive = true, 
                                	ProductCode='EXLifetime',
                                	Family = 'Storage');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'My Genome - Premium', 
                                	IsActive = true, 
                                	ProductCode='MGP',
                                	Family = 'Product',
                                    Is_Genomics_Product__c=true);
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'My Genome - Premium + Newborn Panel', 
                                	IsActive = true, 
                                	ProductCode='MM',
                                	Family = 'Product',
                                    Is_Genomics_Product__c=true);
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'My Genome - Standard', 
                                	IsActive = true, 
                                	ProductCode='MGS',
                                	Family = 'Product',
                                    Is_Genomics_Product__c=true);
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Newborn Panel', 
                                	IsActive = true, 
                                	ProductCode='NBP',
                                	Family = 'Product',
                                    Is_Genomics_Product__c=true);
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Placenta 20yr Storage', 
                                	IsActive = true, 
                                	ProductCode='P20Yr',
                                	Family = 'Storage');
        productsForInsert.add ( prod );

        prod = new Product2 (Name = 'Placenta Lifetime Storage', 
                                	IsActive = true, 
                                	ProductCode='PLifetime',
                                	Family = 'Storage');
        productsForInsert.add ( prod );
        
        insert productsForInsert;
        
        Map < string, sObject > productMap = Toolkit.indexedSObjectMap ( productsForInsert, 'ProductCode' );
        
        // Create Pricebook Entries
        List < PricebookEntry > pricebookEntriesForInsert = new List < PricebookEntry > ();
        
        PricebookEntry standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                                           Product2Id = (Id) productMap.get ( 'CB' ).get ( 'Id' ),
                                                           UnitPrice = 1600, 
                                                           IsActive = true);
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                                           Product2Id = (Id) productMap.get ( 'CB' ).get ( 'Id' ),
                                                           UnitPrice = 1600, 
                                                           IsActive = true);
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                                           Product2Id = (Id) productMap.get ( 'CT' ).get ( 'Id' ),
                                                           UnitPrice = 1600, 
                                                           IsActive = true);
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                                           Product2Id = (Id) productMap.get ( 'CT' ).get ( 'Id' ),
                                                           UnitPrice = 1600, 
                                                           IsActive = true);
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                                            Product2Id = (Id) productMap.get ( 'PT' ).get ( 'Id' ),
                                                            UnitPrice = 1600, 
                                                            IsActive = true);
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                                            Product2Id = (Id) productMap.get ( 'PT' ).get ( 'Id' ),
                                                            UnitPrice = 1600, 
                                                            IsActive = true);
        pricebookEntriesForInsert.add ( standardPrice );

        				standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                                           Product2Id = (Id) productMap.get ( 'CBCT' ).get ( 'Id' ),
                                                           UnitPrice = 2600, 
                                                           IsActive = true);
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                                           Product2Id = (Id) productMap.get ( 'CBCT' ).get ( 'Id' ),
                                                           UnitPrice = 2600, 
                                                           IsActive = true);
        pricebookEntriesForInsert.add ( standardPrice );
        
        				standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTP' ).get ( 'Id' ),
                                            UnitPrice = 3100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTP' ).get ( 'Id' ),
                                            UnitPrice = 3100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );
                        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                    Product2Id = (Id) productMap.get ( 'CBCTPEX' ).get ( 'Id' ),
                                    UnitPrice = 3100, 
                                    IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPEX' ).get ( 'Id' ),
                                            UnitPrice = 3100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );
                		
        
                        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPEXMM' ).get ( 'Id' ),
                                            UnitPrice = 3822, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPEXMM' ).get ( 'Id' ),
                                            UnitPrice = 3822, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );
                				
                        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'EX' ).get ( 'Id' ),
                                            UnitPrice = 3100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'EX' ).get ( 'Id' ),
                                            UnitPrice = 3100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                				standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'MGP' ).get ( 'Id' ),
                                            UnitPrice = 3100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'MGP' ).get ( 'Id' ),
                                            UnitPrice = 3100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );


                				standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'MGS' ).get ( 'Id' ),
                                            UnitPrice = 3100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'MGS' ).get ( 'Id' ),
                                            UnitPrice = 3100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                                            Product2Id = (Id) productMap.get ( 'NBP' ).get ( 'Id' ),
                                                            UnitPrice = 3100, 
                                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'NBP' ).get ( 'Id' ),
                                            UnitPrice = 3100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

        				standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CB20Yr' ).get ( 'Id' ),
                                            UnitPrice = 1700, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CB20Yr' ).get ( 'Id' ),
                                            UnitPrice = 1700, 
                                            IsActive = true);

        pricebookEntriesForInsert.add ( standardPrice );
        
        				standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCT20Yr' ).get ( 'Id' ),
                                            UnitPrice = 3100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCT20Yr' ).get ( 'Id' ),
                                            UnitPrice = 3100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

        				standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTP20Yr' ).get ( 'Id' ),
                                            UnitPrice = 3500, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTP20Yr' ).get ( 'Id' ),
                                            UnitPrice = 3500, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );
        
        				
        				standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBLifetime' ).get ( 'Id' ),
                                            UnitPrice = 3500, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBLifetime' ).get ( 'Id' ),
                                            UnitPrice = 3500, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );
        
        				standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTLifetime' ).get ( 'Id' ),
                                            UnitPrice = 6300, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTLifetime' ).get ( 'Id' ),
                                            UnitPrice = 6300, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );
        
        				standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPLifetime' ).get ( 'Id' ),
                                            UnitPrice = 7100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPLifetime' ).get ( 'Id' ),
                                            UnitPrice = 7100, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPEXMM20Yr' ).get ( 'Id' ),
                                            UnitPrice = 4399, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPEXMM20Yr' ).get ( 'Id' ),
                                            UnitPrice = 4399, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPEXMMLifetime' ).get ( 'Id' ),
                                            UnitPrice = 9099, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPEXMMLifetime' ).get ( 'Id' ),
                                            UnitPrice = 9099, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );
        
        				standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'RushShip' ).get ( 'Id' ),
                                            UnitPrice = 200, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'RushShip' ).get ( 'Id' ),
                                            UnitPrice = 200, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );
        
                        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'StndShip' ).get ( 'Id' ),
                                            UnitPrice = 79, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'StndShip' ).get ( 'Id' ),
                                            UnitPrice = 79, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );
        
        				standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CollKit' ).get ( 'Id' ),
                                            UnitPrice = 199, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CollKit' ).get ( 'Id' ),
                                            UnitPrice = 199, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );



        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPEX20Yr' ).get ( 'Id' ),
                                            UnitPrice = 199, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPEX20Yr' ).get ( 'Id' ),
                                            UnitPrice = 199, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );




        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPEXLifetime' ).get ( 'Id' ),
                                            UnitPrice = 199, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'CBCTPEXLifetime' ).get ( 'Id' ),
                                            UnitPrice = 199, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );


        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'EX20Yr' ).get ( 'Id' ),
                                            UnitPrice = 199, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'EX20Yr' ).get ( 'Id' ),
                                            UnitPrice = 199, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );


        standardPrice = new PricebookEntry (Pricebook2Id = standardPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'EXLifetime' ).get ( 'Id' ),
                                            UnitPrice = 199, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );

                        standardPrice = new PricebookEntry (Pricebook2Id = customPriceBookId, 
                                            Product2Id = (Id) productMap.get ( 'EXLifetime' ).get ( 'Id' ),
                                            UnitPrice = 199, 
                                            IsActive = true);
        
        pricebookEntriesForInsert.add ( standardPrice );


        insert pricebookEntriesForInsert;

        // Items for Kulterra
        // Payment Center Settings
        fw1__Payment_Center_Setting__c s = new fw1__Payment_Center_Setting__c();
        s.Name = 'Default Settings';
        insert s;
        
        fw1.PackagedData.restoreStripeData();

        // Payment Center Ext Settings
        fw2__Payment_Center_Extension_Settings__c ext = new fw2__Payment_Center_Extension_Settings__c();
        ext.fw2__Do_Not_Copy_Line_Items__c = true;
        insert ext;

        // Create Ambassador Account
        Account ambassador = new Account();
        ambassador.Name = 'Ambassador Account';
        insert ambassador;
        
        // create custom setting - Americord_Settings__c 
        // https://developer.salesforce.com/forums/?id=906F000000092ynIAA
        Americord_Settings__c acs = new Americord_Settings__c();
        	acs.Current_Price_Book__c = customPriceBookId;
            acs.Deposit_Amount__c = 199;
            acs.Ambassador_Account_ID__c = ambassador.id;
 	     	insert acs;
 
			    
    }

    // object creation

    public static Opportunity createOpportunity ( string oppName, string stageName, boolean insertObject ) {

        // Create an account
        Account a = new Account();
        a.Name = 'Test Account';
        insert a;
        
        //create contact
        Contact c = new Contact();
        c.AccountId = a.Id;
        c.FirstName = 'testxx';
        c.LastName = 'testxx';
        c.Email = 'testxx@test.com';
        insert c;

        // Create an opportunity
        User u = getCurrentSalesRep();

        Opportunity o = new Opportunity ();
        o.Name = oppName;
        o.OwnerId = u.Id;
        o.StageName = stageName;
        o.CloseDate = Date.today();
        o.AccountId = a.Id;
        o.Number_of_Births__c = 'Single';
        o.Cord_Blood_2_0__c = 1;
        o.Cord_Tissue__c = 1;
        o.Placenta_2_0__c = 0;
        o.Storage_Plan__c = '20YPP';
        o.Payment_Plans__c = 'OTP';
        o.Contact__c = c.id;
        o.Email__c = 'mary@test.com';
        o.FirstName__c = 'Mary';
        o.LastName__c = 'Test';
        o.Relation_to_Baby__c = 'Mother';        
        o.Referred_by_email_address__c = 'john@test.com';
        o.Referred_by_First_Name__c = 'JOHN';
        o.Referred_by_Last_Name__c = 'DOE';
        o.Shipping_Street__c = '123 main st';
        o.Shipping_City__c = 'Chicago';
        o.Shipping_Country__c = 'US';
        o.Shipping_State_Province__c = 'IL';
        o.Shipping_Zip__c = '99999';
        o.Authorized_Payment__c = true;

        if ( insertObject ) {
            insert o;
        }
        
        return o;
    }

    public static User getCurrentSalesRep() {
        Schema.SObjectType s = Schema.getGlobalDescribe().get('fw1__Invoice__c') ;
        Schema.DescribeSObjectResult r = s.getDescribe() ;
        Map<String,Schema.SObjectField> fields = r.fields.getMap() ;
        Schema.DescribeFieldResult fieldResult = fields.get('Sales_rep__c').getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

        System.debug('ple[0].getLabel() +' +ple[0].getValue());

        User u = [SELECT ID FROM User WHERE CommunityNickname=:ple[0].getValue()];
        return u;
    }

    // getters
    public static fw1__Invoice__c getInvoice(string opptyId) {
        List<fw1__Invoice__c> invs = new List<fw1__Invoice__c>();
        invs = [
            SELECT fw1__Account__c,Cord_Blood_2_0_Stored__c,Cord_Tissue_Stored__c,Placenta_2_0_Stored__c,Placenta_Tissue_Stored__c,
            Cord_Blood_2_0_Ordered__c,Cord_Tissue_Ordered__c,Placenta_2_0_Ordered__c,Placenta_Tissue_Ordered__c,
            Lab__c,Lab__r.Cord_Blood_Collection_Completed__c,Storage_Plan_Ordered__c,Payment_Plan_Ordered__c,
            Storage_Plan_Stored__c,Payment_Plan_Stored__c,fw1__Total_Lines_Count__c
            FROM fw1__Invoice__c
            WHERE fw2__Opportunity__c = :opptyId
        ];
        
        if (invs.size() > 0)
        	return invs[0];
        else
            return null;
    }
}