force-app/main/default/objects/Americord_Integration_Setting__mdt/Americord_Integration_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata contains values for use with integrations between SF and other systems.</description>
    <label>Americord Integration Setting</label>
    <pluralLabel>Ameircord Integration Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Header_Code__c.field-meta.xml
<CustomField>
    <fullName>Genome_Header_Code__c</fullName>
    <label>Genome Header Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Header_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Genome_Header_Endpoint__c</fullName>
    <label>Genome Header Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Header_FullURL__c.field-meta.xml
<CustomField>
    <fullName>Genome_Header_FullURL__c</fullName>
    <label>Genome Header FullURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Header_System__c.field-meta.xml
<CustomField>
    <fullName>Genome_Header_System__c</fullName>
    <label>Genome Header System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Patient_Extension_Ethnicity__c.field-meta.xml
<CustomField>
    <fullName>Genome_Patient_Extension_Ethnicity__c</fullName>
    <label>Genome Patient Extension Ethnicity</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Patient_Extension_Ethnicity_URL__c.field-meta.xml
<CustomField>
    <fullName>Genome_Patient_Extension_Ethnicity_URL__c</fullName>
    <label>Genome Patient Extension Ethnicity URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Patient_Extension_Race__c.field-meta.xml
<CustomField>
    <fullName>Genome_Patient_Extension_Race__c</fullName>
    <label>Genome Patient Extension Race</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Patient_Extension_Race_URL__c.field-meta.xml
<CustomField>
    <fullName>Genome_Patient_Extension_Race_URL__c</fullName>
    <label>Genome Patient Extension Race URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Patient_FullURL__c.field-meta.xml
<CustomField>
    <fullName>Genome_Patient_FullURL__c</fullName>
    <label>Genome Patient FullURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Service_Request_Product_Code_MyG__c.field-meta.xml
<CustomField>
    <fullName>Genome_Service_Request_Product_Code_MyG__c</fullName>
    <description>Product code MyGenome.</description>
    <inlineHelpText>Product code MyGenome.</inlineHelpText>
    <label>Genome Service Request Product Code MyG</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Service_Request_Product_Code_MyN__c.field-meta.xml
<CustomField>
    <fullName>Genome_Service_Request_Product_Code_MyN__c</fullName>
    <description>Product code for MyNewborn.</description>
    <inlineHelpText>Product code for MyNewborn.</inlineHelpText>
    <label>Genome Service Request Product Code MyN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Service_Request_Product_System__c.field-meta.xml
<CustomField>
    <fullName>Genome_Service_Request_Product_System__c</fullName>
    <label>Genome Service Request Product System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Service_Request_Program_MyG_Prem__c.field-meta.xml
<CustomField>
    <fullName>Genome_Service_Request_Program_MyG_Prem__c</fullName>
    <description>This is the code for My Genome Premium</description>
    <inlineHelpText>This is the code for My Genome Premium</inlineHelpText>
    <label>Genome Service Request Program MyG Prem</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Service_Request_Program_MyG_Stnd__c.field-meta.xml
<CustomField>
    <fullName>Genome_Service_Request_Program_MyG_Stnd__c</fullName>
    <description>This is the program code for My Genome Standard.</description>
    <inlineHelpText>This is the program code for My Genome Standard.</inlineHelpText>
    <label>Genome Service Request Program MyG Stnd</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Americord_Integration_Setting__mdt/fields/Genome_Service_Request_Program_MyN_Panel__c.field-meta.xml
<CustomField>
    <fullName>Genome_Service_Request_Program_MyN_Panel__c</fullName>
    <description>This is the program code for the My Newborn Panel product.</description>
    <inlineHelpText>This is the program code for the My Newborn Panel product.</inlineHelpText>
    <label>Genome Service Request Program MyN Panel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Baby__c/Baby__c.object-meta.xml
<CustomObject>
    <label>Family Member</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Baby__c/fields/Baby_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Baby_First_Name__c</fullName>
    <formula>IF (
OR (
CONTAINS(Name_of_Child__c, &quot;Baby&quot;),
CONTAINS(Name_of_Child__c, &quot;Twin&quot;),
CONTAINS(Name_of_Child__c, &quot;UNA&quot;),
CONTAINS(Name_of_Child__c, &quot;Unknown&quot;),
CONTAINS(Name_of_Child__c, &quot;Female&quot;),
ISBLANK(Name_of_Child__c)),
null,
LEFT( Name_of_Child__c  ,FIND(&quot; &quot;, Name_of_Child__c,1)-1))</formula>
    <inlineHelpText>Returns only the first name upto the first space in the full name of child field.</inlineHelpText>
    <label>Baby First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/Lab__c.field-meta.xml
<CustomField>
    <fullName>Lab__c</fullName>
    <label>Lab</label>
    <referenceTo>Lab__c</referenceTo>
    <relationshipName>Baby</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Baby__c/fields/LPI_My_Genome__c.field-meta.xml
<CustomField>
    <fullName>LPI_My_Genome__c</fullName>
    <description>This is the kit id for the My Genome sample.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the kit id for the My Genome sample.</inlineHelpText>
    <label>LPI My Genome</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Baby__c/fields/LPI_My_Newborn__c.field-meta.xml
<CustomField>
    <fullName>LPI_My_Newborn__c</fullName>
    <description>This is the kit id for the My Newborn sample.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the kit id for the My Newborn sample.</inlineHelpText>
    <label>Newborn Client ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Baby__c/fields/Mother_s_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_First_Name__c</fullName>
    <formula>Lab__r.Mother_s_First_Name__c</formula>
    <label>Mother&apos;s First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/Mother_s_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_Last_Name__c</fullName>
    <description>LU field from the Lab page, used for Genomics Permissions letter.</description>
    <formula>Lab__r.Mother_s_Last_Name__c</formula>
    <label>Mother&apos;s Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Baby__c/fields/Sex_of_Child__c.field-meta.xml
<CustomField>
    <fullName>Sex_of_Child__c</fullName>
    <label>Sex of Child</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Non-Binary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab__c/Lab__c.object-meta.xml
<CustomObject>
    <label>Lab</label>
    <nameField>
        <label>Lab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Labs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab__c/fields/Birth_Date_from_Courier__c.field-meta.xml
<CustomField>
    <fullName>Birth_Date_from_Courier__c</fullName>
    <inlineHelpText>Provided via call center or digital courier pick-up</inlineHelpText>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Cord_Blood_Order__c.field-meta.xml
<CustomField>
    <fullName>Cord_Blood_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cord Blood Order</label>
    <referenceTo>fw1__Invoice__c</referenceTo>
    <relationshipLabel>Labs</relationshipLabel>
    <relationshipName>Labs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Mother_s_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_First_Name__c</fullName>
    <inlineHelpText>Syncs with Contact info using a trigger</inlineHelpText>
    <label>Contact First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Mother_s_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_Last_Name__c</fullName>
    <inlineHelpText>Syncs with Contact info using a trigger</inlineHelpText>
    <label>Contact Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Mother_s_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_Phone__c</fullName>
    <inlineHelpText>Syncs with Contact info using a trigger</inlineHelpText>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Mothers_Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Mothers_Date_Of_Birth__c</fullName>
    <label>Contact Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Mothers_Email__c.field-meta.xml
<CustomField>
    <fullName>Mothers_Email__c</fullName>
    <inlineHelpText>Syncs with Contact info using a trigger</inlineHelpText>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>Shipping City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <defaultValue>&quot;US&quot;</defaultValue>
    <label>Shipping Country old</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_State_new__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State_new__c</fullName>
    <label>Shipping State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_Street__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Street__c</fullName>
    <label>Shipping Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Shipping_Zip__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Zip__c</fullName>
    <label>Shipping Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenomeOrderHelper.cls
public with sharing class GenomeOrderHelper {
    /**
    * constructGenomeOrder
    * -------
    * @param babyRecord Baby record to use for the order.
    * @param strOrderType Order type    
    * @param strOrderLevel Order level (Premium, Standard)
    * @return strBody Formatted body for callout.
    */
    public static String constructGenomeOrder(Baby__c babyRecord, String strOrderType, String strOrderLevel){
        String strBody;
        
        Americord_Integration_Setting__mdt americordIntegSetting = getCurrentIntegrationSettings();

        // HEADER
        GenomeOrder.GenomeOrderMessageHeaderResourceEventCoding genmsghdrec = new GenomeOrder.GenomeOrderMessageHeaderResourceEventCoding();
        genmsghdrec.system_AMERICORD = americordIntegSetting.Genome_Header_System__c;
        genmsghdrec.code = americordIntegSetting.Genome_Header_Code__c ;

        GenomeOrder.GenomeOrderMessageHeaderSource genmsghdsrc = new GenomeOrder.GenomeOrderMessageHeaderSource();
        genmsghdsrc.endpoint = americordIntegSetting.Genome_Header_Endpoint__c;

        GenomeOrder.GenomeOrderMessageHeaderResource genmsghdres = new GenomeOrder.GenomeOrderMessageHeaderResource();
        genmsghdres.eventCoding = genmsghdrec;
        genmsghdres.source = genmsghdsrc;
        genmsghdres.resourceType = 'MessageHeader';

        GenomeOrder.GenomeOrderMessageHeader genmsghdr = new GenomeOrder.GenomeOrderMessageHeader();
        genmsghdr.fullUrl = americordIntegSetting.Genome_Header_FullURL__c;
        genmsghdr.resource = genmsghdres;

        // PATIENT
        GenomeOrder.GenomePatientIdentifier genpid = new GenomeOrder.GenomePatientIdentifier();
        if (strOrderType == 'MYGENOME'){
            genpid.value = babyRecord.LPI_My_Genome__c;
        }
        if (strOrderType == 'MYNEWBORN') {
            genpid.value = babyRecord.LPI_My_Newborn__c;
        }

        GenomeOrder.GenomePatientName genpname = new GenomeOrder.GenomePatientName();
        List<String> lstGivenNames = new List<String>();     
        genpname.family = babyRecord.Mother_s_Last_Name__c;
        if(strOrderType == 'MYGENOME'){
            lstGivenNames.add(babyRecord.Mother_s_First_Name__c);
        }
        if(strOrderType == 'MYNEWBORN'){
            if (babyRecord.Baby_First_Name__c == null){
                lstGivenNames.add(babyRecord.Name.replace(' '+babyRecord.Mother_s_Last_Name__c, '')); //tricky subst here
            }
            else{
                lstGivenNames.add(babyRecord.Baby_First_Name__c);
            }            
        }
        genpname.given = lstGivenNames;

        GenomeOrder.GenomePatientTelecom genptel = new GenomeOrder.GenomePatientTelecom();
        genptel.system_AMERICORD = 'phone';
        genptel.value = babyRecord.Lab__r.Mother_s_Phone__c;

        GenomeOrder.GenomePatientTelecom genptelemail = new GenomeOrder.GenomePatientTelecom();
        genptelemail.system_AMERICORD = 'email';
        genptelemail.value = babyRecord.Lab__r.Mothers_Email__c;

        GenomeOrder.GenomePatientAddress genpadd = new GenomeOrder.GenomePatientAddress();
        List<String> lstAddressLine = new List<String>();
        lstAddressLine.add(babyRecord.Lab__r.Shipping_Street__c);
        genpadd.line = lstAddressLine;
        genpadd.city = babyRecord.Lab__r.Shipping_City__c;
        genpadd.state = babyRecord.Lab__r.Shipping_State_new__c;
        genpadd.postalCode = babyRecord.Lab__r.Shipping_Zip__c;
        genpadd.country = babyRecord.Lab__r.Shipping_Country__c;

        GenomeOrder.GenomePatientExtension genpext = new GenomeOrder.GenomePatientExtension();

        GenomeOrder.GenomePatientResource genpres = new GenomeOrder.GenomePatientResource();
        List<GenomeOrder.GenomePatientAddress> lstPatAddress = new List<GenomeOrder.GenomePatientAddress>();
        List<GenomeOrder.GenomePatientExtension> lstPatExt = new List<GenomeOrder.GenomePatientExtension>();
        List<GenomeOrder.GenomePatientIdentifier> lstPatId = new LIst<GenomeOrder.GenomePatientIdentifier>();
        List<GenomeOrder.GenomePatientName> lstPatName = new List<GenomeOrder.GenomePatientName>();
        List<GenomeOrder.GenomePatientTelecom> lstPatTel = new List<GenomeOrder.GenomePatientTelecom>();

        lstPatAddress.add(genpadd);
        genpres.address = lstPatAddress;

        lstPatExt.add(genpext);
        genpres.extension = lstPatExt;

        lstPatId.add(genpid);
        genpres.identifier = lstPatId;

        lstPatName.add(genpname);
        genpres.name = lstPatName;

        lstPatTel.add(genptel);
        lstPatTel.add(genptelemail);
        genpres.telecom = lstPatTel;

        if(strOrderType == 'MYGENOME'){
            genpres.birthDate = String.valueOf(babyRecord.Lab__r.Mothers_Date_Of_Birth__c);
            genpres.gender = 'Female';
        }
        if(strOrderType == 'MYNEWBORN'){
            if(babyRecord.Lab__r.Birth_Date_from_Courier__c == null){
                genpres.birthDate = String.valueOf(babyRecord.Lab__r.Cord_Blood_Order__r.fw1__Invoice_Date__c);
            }
            else{
                genpres.birthDate = String.valueOf(babyRecord.Lab__r.Birth_Date_from_Courier__c);
            }
            
            if(babyRecord.Sex_of_Child__c == null){
                genpres.gender = 'Unavailable';
            }
            else{
                genpres.gender = babyRecord.Sex_of_Child__c;
            }
            
        }        

        

        // DEMOGRAPHICS NOT USED - FILLING OUT OF COMPLETENESS
        GenomeOrder.GenomePatientExtension genpextdemorace = new GenomeOrder.GenomePatientExtension();
        GenomeOrder.GenomePatientExtension genpextdemoeth = new GenomeOrder.GenomePatientExtension();
        String strDemoRace = americordIntegSetting.Genome_Patient_Extension_Race__c;
        String strDemoEth = americordIntegSetting.Genome_Patient_Extension_Ethnicity__c;

        List<String> lstDemoRace = new List<String>();
        List<String> lstDemoEth = new List<String>();
        lstDemoRace.add(strDemoRace);        
        genpextdemorace.extension = lstDemoRace;
        genpextdemorace.url = americordIntegSetting.Genome_Patient_Extension_Race_URL__c;

        lstDemoEth.add(strDemoEth);
        genpextdemoeth.extension = lstDemoEth;
        genpextdemoeth.url = americordIntegSetting.Genome_Patient_Extension_Ethnicity_URL__c;

        genpres.extension.add(genpextdemorace);        
        genpres.extension.add(genpextdemoeth);

        genpres.resourceType = 'Patient';

        GenomeOrder.GenomePatient genp = new GenomeOrder.GenomePatient();
        genp.fullURL = americordIntegSetting.Genome_Patient_FullURL__c;
        genp.resource = genpres;        

        // SERIVCE REQUEST
        GenomeOrder.GenomeServiceRequestSubject gensrvreqsub = new GenomeOrder.GenomeServiceRequestSubject();
        if(strOrderType == 'MYGENOME'){
            gensrvreqsub.reference = 'Patient\\'+babyRecord.LPI_My_Genome__c;
        }
        if(strOrderType == 'MYNEWBORN'){
            gensrvreqsub.reference = 'Patient\\'+babyRecord.LPI_My_Newborn__c;
        }
        
        GenomeOrder.GenomeServiceRequestCodeEntry gensrvreqcodeentry_product = new GenomeOrder.GenomeServiceRequestCodeEntry();
        if(strOrderType == 'MYGENOME'){
            gensrvreqcodeentry_product.code=americordIntegSetting.Genome_Service_Request_Product_Code_MyG__c;
        }
        if(strOrderType == 'MYNEWBORN'){
            gensrvreqcodeentry_product.code=americordIntegSetting.Genome_Service_Request_Product_Code_MyN__c;
        }

        gensrvreqcodeentry_product.system_AMERICORD = americordIntegSetting.Genome_Service_Request_Product_System__c;

        GenomeOrder.GenomeServiceRequestCodeEntry gensrvreqcodeentry_program = new GenomeOrder.GenomeServiceRequestCodeEntry();

        if(strOrderType == 'MYGENOME' && strOrderLevel == 'STANDARD'){
            gensrvreqcodeentry_program.code=americordIntegSetting.Genome_Service_Request_Program_MyG_Stnd__c;    
        }
        else if (strOrderType == 'MYGENOME' && strOrderLevel == 'PREMIUM'){
            gensrvreqcodeentry_program.code=americordIntegSetting.Genome_Service_Request_Program_MyG_Prem__c;    
        }
        else if(strOrderType == 'MYNEWBORN' && strOrderLevel == 'PANEL'){
            gensrvreqcodeentry_program.code=americordIntegSetting.Genome_Service_Request_Program_MyN_Panel__c;  
        }
        
        gensrvreqcodeentry_program.system_AMERICORD = americordIntegSetting.Genome_Service_Request_Program_System__c;

        GenomeOrder.GenomeServiceRequestCodeEntry gensrvreqcodeentry_client = new GenomeOrder.GenomeServiceRequestCodeEntry();
        if(strOrderType == 'MYGENOME' && strOrderLevel == 'STANDARD'){
            gensrvreqcodeentry_client.code=americordIntegSetting.Genome_Service_Request_Client_Code__c; 
        }
        else if (strOrderType == 'MYGENOME' && strOrderLevel == 'PREMIUM'){
            gensrvreqcodeentry_client.code=americordIntegSetting.Genome_Service_Request_Client_Code__c;    
        }
        else if(strOrderType == 'MYNEWBORN' && strOrderLevel == 'PANEL'){
            gensrvreqcodeentry_client.code=americordIntegSetting.Genome_Service_Request_Client_Code_Nwbrn__c;  
        }        
        
        gensrvreqcodeentry_client.system_AMERICORD = americordIntegSetting.Genome_Service_Request_Client_System__c;
        
        GenomeOrder.GenomeServiceRequestCode gensrvreqcode = new GenomeOrder.GenomeServiceRequestCode();
        List<GenomeOrder.GenomeServiceRequestCodeEntry> lstCodeEntry = new List<GenomeOrder.GenomeServiceRequestCodeEntry>();
        lstCodeEntry.add(gensrvreqcodeentry_product);
        lstCodeEntry.add(gensrvreqcodeentry_program);
        lstCodeEntry.add(gensrvreqcodeentry_client);
        gensrvreqcode.coding = lstCodeEntry;

        GenomeOrder.GenomeServiceRequestResourceIdentifier gensrvreqresid = new GenomeOrder.GenomeServiceRequestResourceIdentifier();
        if(strOrderType == 'MYGENOME'){
            gensrvreqresid.value = babyRecord.LPI_My_Genome__c;
        }
        if(strOrderType == 'MYNEWBORN'){
            gensrvreqresid.value = babyRecord.LPI_My_Newborn__c;
        }

        GenomeOrder.GenomeServiceRequestResource gensrvreqres = new GenomeOrder.GenomeServiceRequestResource();
        List<GenomeOrder.GenomeServiceRequestResourceIdentifier> lstServReqResId = new List<GenomeOrder.GenomeServiceRequestResourceIdentifier>();
        lstServReqResId.add(gensrvreqresid);        
        gensrvreqres.resourceType = 'ServiceRequest';
        gensrvreqres.identifier = lstServReqResId;
        gensrvreqres.intent = americordIntegSetting.Genome_Service_Request_Resource_Intent__c;
        gensrvreqres.status = americordIntegSetting.Genome_Service_Request_Resource_Status__c;
        gensrvreqres.code = gensrvreqcode;
        gensrvreqres.subject = gensrvreqsub;

        GenomeOrder.GenomeServiceRequest gensrvreq = new GenomeOrder.GenomeServiceRequest();
        gensrvreq.fullUrl = americordIntegSetting.Genome_Service_Request_FullURL__c;
        gensrvreq.resource = gensrvreqres;        

        // PRACTITIONER -- not used but build out for complete message
        GenomeOrder.GenomePractitionerIdentifier genprid = new GenomeOrder.GenomePractitionerIdentifier();
        genprid.system_AMERICORD = null;
        genprid.value = null;
        List<GenomeOrder.GenomePractitionerIdentifier> lstgenprid = new List<GenomeOrder.GenomePractitionerIdentifier>();
        lstgenprid.add(genprid);

        GenomeOrder.GenomePractitionerName genprname = new GenomeOrder.GenomePractitionerName();
        genprname.family = null;
        List<String> lstPrGivenNames = new List<String>();
        genprname.given = lstPrGivenNames;
        
        List<GenomeOrder.GenomePractitionerName> lstgenprname = new List<GenomeOrder.GenomePractitionerName>();
        lstgenprname.add(genprname);

        GenomeOrder.GenomePractitionerResource genprres = new GenomeOrder.GenomePractitionerResource();
        GenomeOrder.GenomePracticioner genpr = new GenomeOrder.GenomePracticioner();
        genprres.identifier = lstgenprid;
        genprres.name = lstgenprname;
        genprres.resourceType = 'Practitioner';
        genpr.fullUrl = americordIntegSetting.Genome_Practitioner_FullURL__c;
        genpr.resource = genprres;
        
        // SPECIMEN
        GenomeOrder.GenomeSpecimenResourceCollection genspecrescol = new GenomeOrder.GenomeSpecimenResourceCollection();
        if(babyRecord.Collection_Date__c != null){
            genspecrescol.collectedDateTime = babyRecord.Collection_Date__c.year()+'-'+babyRecord.Collection_Date__c.month()+'-'+babyRecord.Collection_Date__c.day()+'T00:00:00.000Z'; //we dont have a datetime collection field
        }        

        GenomeOrder.GenomeSpecimenResourceTypeCoding genspecrestypecode = new GenomeOrder.GenomeSpecimenResourceTypeCoding();
        genspecrestypecode.code = americordIntegSetting.Genome_Specimen_Resource_Code_Code__c;
        genspecrestypecode.display = americordIntegSetting.Genome_Specimen_Resource_Code_Display__c;
        genspecrestypecode.system_AMERICORD = americordIntegSetting.Genome_Specimen_Resource_Code_System__c;

        GenomeOrder.GenomeSpecimenResourceType genspecrestype = new GenomeOrder.GenomeSpecimenResourceType();
        List<GenomeOrder.GenomeSpecimenResourceTypeCoding> lstspeccode = new List<GenomeOrder.GenomeSpecimenResourceTypeCoding>();
        lstspeccode.add(genspecrestypecode);
        genspecrestype.coding = lstspeccode;

        GenomeOrder.GenomeSpecimenResourceIdentifier genspecresid = new GenomeOrder.GenomeSpecimenResourceIdentifier();
        if(strOrderType == 'MYGENOME'){
            genspecresid.value = babyRecord.ISBT_My_Genome__c;
        }
        if(strOrderType == 'MYNEWBORN'){
            genspecresid.value = babyRecord.ISBT_My_Newborn__c;
        }

        GenomeOrder.GenomeSpecimenResource genspecres = new GenomeOrder.GenomeSpecimenResource();
        List<GenomeOrder.GenomeSpecimenResourceIdentifier> lstSpecResIds = new List<GenomeOrder.GenomeSpecimenResourceIdentifier>();
        lstSpecResIds.add(genspecresid);
        genspecres.collection = genspecrescol;
        genspecres.identifier = lstSpecResIds;
        genspecres.type = genspecrestype;
        genspecres.resourceType = 'Specimen';

        GenomeOrder.GenomeSpecimen genspec = new GenomeOrder.GenomeSpecimen();
        genspec.fullUrl = americordIntegSetting.Genome_Specimen_FullURL__c;
        genspec.resource = genspecres;

        // Build Entries
        List<String> lstEntry = new List<String>(); 

        lstEntry.add(cleanReservedWordsInString(JSON.serialize(genmsghdr)));
        lstEntry.add(cleanReservedWordsInString(JSON.serialize(genp)));
        lstEntry.add(cleanReservedWordsInString(JSON.serialize(gensrvreq)));
        lstEntry.add(cleanReservedWordsInString(JSON.serialize(genpr)));
        lstEntry.add(cleanReservedWordsInString(JSON.serialize(genspec)));

        

        // main message
        GenomeOrder.GenomeOrderMessage genmsg = new GenomeOrder.GenomeOrderMessage();
        genmsg.entry = lstEntry;
        genmsg.resourceType = 'Bundle';
        genmsg.type = 'message';

        strBody = cleanDoubleQuotesInJSONString(JSON.serialize(genmsg));
        
        System.debug('==== Genome Integration Values ====');
        System.debug('Order Type:'+strOrderType);
        System.debug('Order Level:'+strOrderLevel);
        System.debug('Client Code:'+gensrvreqcodeentry_client.code);
        System.debug('Program ID:'+gensrvreqcodeentry_program.code);
        System.debug('Genome FHIR Message:'+strBody);

        return strBody;
    }

    /**
    * clearReservedWordsInString
    * -------
    * @param strInput incoming string to clean
    * @return strReturnString return string cleaned
    */
    private static String cleanReservedWordsInString(String strInput){
        String strReturnString = strInput.replaceAll('_AMERICORD', '');
        strReturnString = strReturnString.replaceAll(':null', ':""');
        return strReturnString;
    }    

    /**
    * getSignupURLFromResponse
    * -------
    * @param strResponse Response from callout
    * @return strSignupURL URL that will be used to send to cusomer for singup.
    */
    public static String getSignupURLFromResponse(String strResponse){
        String strSignupURL;
        List<Map<String,Object>> mapEntryData = new List<Map<String,Object>>();
        List<Object> lstID = new List<Object>();
        List<Object> lstURL = new List<Object>();        
        String strResponseClean = cleanDoubleQuotesInJSONString(strResponse);
        Map<String,Object> mapResponse = (Map<String,Object>)JSON.deserializeUntyped(strResponseClean);
        Map<String,Object> mapBody = (Map<String,Object>)mapResponse.get('body');
        List<Object> lstEntry = (List<Object>)mapBody.get('entry');


        for(Object obj : lstEntry){
            mapEntryData.add((Map<String,Object>)obj);    
        }
        for(Map<String,Object> mapEntry : mapEntryData){
            for(String strKey :  mapEntry.keySet()){
                if(strKey == 'resourceType'){
                    if((String)mapEntry.get(strKey) == 'SignupURL'){
                        lstID = (List<Object>)mapEntry.get('identifier');
                    }
                    if(!lstID.isEmpty()){
                        Map<String,Object> mapURL = (Map<String,Object>)lstID[0];
                        strSignupURL = (String)mapURL.get('value');
                    }
                    
                }
            }
        }        

        return strSignupURL;
    }

    /**
    * cleanDoubleQuotesInJSONString
    * -------
    * @param strInput String to be cleaned
    * @return strReturnString String cleaned
    */
    private static String cleanDoubleQuotesInJSONString(String strInput){
        String strReturnString = strInput.replaceAll('\\\\', '');
        strReturnString = strReturnString.replaceAll('"\\{','\\{');
        strReturnString = strReturnString.replaceAll('\\}"','\\}');    
        return strReturnString;  
    }

    /**
    * getCurrentIntegrationSettings
    * -------
    * returns the custom metadata values for use in by apex.
    */
    private static Americord_Integration_Setting__mdt getCurrentIntegrationSettings(){
        Americord_Integration_Setting__mdt americordIntegSetting = [
            SELECT 
            Genome_Header_Code__c,
            Genome_Header_Endpoint__c,
            Genome_Header_FullURL__c,
            Genome_Header_System__c,
            Genome_Patient_Extension_Ethnicity__c,
            Genome_Patient_Extension_Ethnicity_URL__c,
            Genome_Patient_Extension_Race__c,
            Genome_Patient_Extension_Race_URL__c,
            Genome_Patient_FullURL__c,
            Genome_Practitioner_FullURL__c,
            Genome_Service_Request_Client_Code__c,
            Genome_Service_Request_Client_Code_Nwbrn__c,
            Genome_Service_Request_Client_System__c,
            Genome_Service_Request_FullURL__c,
            Genome_Service_Request_Product_Code_MyN__c,
            Genome_Service_Request_Product_Code_MyG__c,
            Genome_Service_Request_Product_System__c,
            Genome_Service_Request_Program_System__c,
            Genome_Service_Request_Resource_Intent__c,
            Genome_Service_Request_Resource_Status__c,
            Genome_Service_Request_Program_MyG_Prem__c,
            Genome_Service_Request_Program_MyG_Stnd__c,
            Genome_Service_Request_Program_MyN_Geno__c,
            Genome_Service_Request_Program_MyN_Panel__c,
            Genome_Specimen_FullURL__c,
            Genome_Specimen_Resource_Code_Code__c,
            Genome_Specimen_Resource_Code_Display__c,
            Genome_Specimen_Resource_Code_System__c
            FROM Americord_Integration_Setting__mdt 
            WHERE label = 'CurrentSettings' LIMIT 1];
            
            return americordIntegSetting;
    }
}