force-app/main/default/objects/Product2/fields/Due_at_Checkout__c.field-meta.xml
<CustomField>
    <fullName>Due_at_Checkout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Some products are paid in full at checkout, such as Kit Fees, Shipping etc.</description>
    <inlineHelpText>Some products are paid in full at checkout, such as Kit Fees, Shipping etc.</inlineHelpText>
    <label>Due at Checkout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Eligible_for_Volume_Discounting__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Volume_Discounting__c</fullName>
    <defaultValue>false</defaultValue>
    <description>There is still a (possibly temporary) mode of discounting based on quantities of Biobanking products selected.  This flag indicates that this product should be included in that calculation and discounting.</description>
    <inlineHelpText>Indicates that this product is subject to automated discounting based on quantity.</inlineHelpText>
    <label>Eligible for Volume Discounting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Is_Biobanking_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_Biobanking_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if this is a Biobanking product OR a bundle including Biobanking product(s)</description>
    <inlineHelpText>True if this is a Biobanking product OR a bundle including Biobanking product(s)</inlineHelpText>
    <label>Is Biobanking Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Partial_Amount_Due_At_Checkout__c.field-meta.xml
<CustomField>
    <fullName>Partial_Amount_Due_At_Checkout__c</fullName>
    <description>Enter an amount if this product should have some portion of its cost due at checkout.  This is distinct from the Due_at_Checkout__c field which indicates a Product&apos;s ENTIRE cost is due up front.</description>
    <label>Partial Amount Due At Checkout</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Test_ProductFactory.cls
@isTest
public class Test_ProductFactory {
    private Product2 current;

    public Test_ProductFactory(Product2 current) {
        this.current = current;
    }

    // Entry point builder method to start composing object attributes- default values for required fields- can be overridden
    public static Test_ProductFactory start() {
        return new Test_ProductFactory(
            new Product2(Name='Test Product',Description='Test Description',Family='Product',IsActive=true,ProductCode='TestCode')
        );
    }

    // Composable Functions
    public Test_ProductFactory overrideName(String name) {
        current.name = name;
        return this;
    }

    public Test_ProductFactory asBiobanking() {
        current.Is_Biobanking_Product__c = true;
        current.Family = 'Product';
        return this;
    }

    public Test_ProductFactory asProduct() {
        current.Family = 'Product';
        return this;
    }

    public Test_ProductFactory asFee() {
        current.Family = 'Maintenance';
        return this;
    }

    public Test_ProductFactory asStorage() {
        current.Family = 'Storage';
        return this;
    }

    public Test_ProductFactory asShipping() {
        current.Family = 'Shipping';
        return this;
    }

    public Test_ProductFactory asKit() {
        current.Family = 'Add-on';
        return this;
    }

    public Test_ProductFactory asDueAtCheckout() {
        current.Due_at_Checkout__c = true;
        return this;
    }

    public Test_ProductFactory withPartialAmtDueAtCheckout(Decimal amt) {
        current.Partial_Amount_Due_at_Checkout__c = amt;
        return this;
    }

    public Test_ProductFactory asEligibleForVolumeDiscounting() {
        current.Eligible_for_Volume_Discounting__c = true;
        return this;
    }

    // Insert the constructed object
    public Product2 create() {
        insert current;
        return current;
    }

    // Return the constructed object without inserting
    public Product2 build() {
        return current;
    }

}