force-app/main/default/objects/Account/fields/fw1__Total_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>fw1__Total_Paid_Amount__c</fullName>
    <label>Total Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Authorized_Payment__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Populated by Process Builder, when Authorization is successful.</inlineHelpText>
    <label>Authorized Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enrollment_Flow_Complete__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Flow_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when the Enrollment Screenflow has been completed.  This will ensure that required fields are entered and the values needed for enrollment are present. Automatically checked by the Enrollment Flow and unchecked if the Stage is changed from Enrolled.</description>
    <label>Enrollment Flow Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/fw1__Total_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>fw1__Total_Paid_Amount__c</fullName>
    <label>Total Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/fw2__Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>fw2__Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>fw1__Payment_Plan__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Impact_Partner_Id__c.field-meta.xml
<CustomField>
    <fullName>Impact_Partner_Id__c</fullName>
    <description>This ID represents if a given lead was obtained via a partner. This value is also referred to as the media ID and represents a partner.</description>
    <inlineHelpText>This ID represents if a given lead was obtained via a partner. This value is also referred to as the media ID and represents a partner.</inlineHelpText>
    <label>Impact Partner Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Number_of_Births__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Births__c</fullName>
    <label>Number of Births</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Twins</fullName>
            </value>
            <value>
                <fullName>Triplets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Number_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Payments__c</fullName>
    <formula>fw2__Payment_Plan__r.Number_of_Payments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Payments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Plans__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plans__c</fullName>
    <label>ZDEPRECATE_Payment Plans</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTP</fullName>
                <label>One-time Payment</label>
            </value>
            <value>
                <fullName>24M</fullName>
                <label>24 Months</label>
            </value>
            <value>
                <fullName>36M</fullName>
                <label>36 Months</label>
            </value>
            <value>
                <fullName>48M</fullName>
                <label>48 Months</label>
            </value>
            <value>
                <fullName>HY18</fullName>
                <label>Hybrid - 18</label>
            </value>
            <value>
                <fullName>12M</fullName>
                <label>12 Months</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Relation_to_Baby__c.field-meta.xml
<CustomField>
    <fullName>Relation_to_Baby__c</fullName>
    <label>Relation to Baby</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>US</label>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State_Province__c</fullName>
    <label>State / Province</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Street__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Street__c</fullName>
    <label>Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Zip__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Zip__c</fullName>
    <label>Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Storage_Plan__c.field-meta.xml
<CustomField>
    <fullName>Storage_Plan__c</fullName>
    <label>Storage Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Storage</fullName>
            </value>
            <value>
                <fullName>20YPP</fullName>
                <label>20 Years Prepaid</label>
            </value>
            <value>
                <fullName>ASP</fullName>
                <label>Annual Storage</label>
            </value>
            <value>
                <fullName>LTS</fullName>
                <label>Lifetime Storage</label>
            </value>
            <value>
                <fullName>Donated</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PartnerConversionTest.cls
@isTest
private class PartnerConversionTest {
    @TestSetup
    static void makeData(){
        AmericordTestDataFactory atdf = new AmericordTestDataFactory();

        // Items for Kulterra
        // Payment Center Settings
        fw1__Payment_Center_Setting__c s = new fw1__Payment_Center_Setting__c();
        s.Name = 'Default Settings';
        insert s;
        
        fw1.PackagedData.restoreStripeData();

        User salesRep = AmericordTestDataFactory.getCurrentSalesRep();

        Account acct = new Account();
        acct.name = 'Test Account';
        insert acct;
        
        Contact cont = new Contact();
        cont.AccountId = acct.id;
        cont.firstname = 'Mary';
        cont.lastname = 'Williamson';
        insert cont;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'TestOpp';
        opp.accountid = acct.id;
        opp.Contact__c = cont.id;
        opp.Email__c = 'mary@test.com';        
        opp.FirstName__c = 'Mary';
        opp.LastName__c = 'Williamson';
        opp.Relation_to_Baby__c = 'Mother';              
        opp.CloseDate = System.today();
        opp.StageName = 'New';
        opp.Authorized_Payment__c = true;        
        opp.ownerid = salesRep.Id;
        opp.Storage_Plan__c = '20YPP';
        opp.Payment_Plans__c = 'OTP';
        opp.Number_of_Births__c = 'Single';        
        opp.Shipping_Street__c = '123 main st';
        opp.Shipping_City__c = 'Chicago';
        opp.Shipping_Country__c = 'US';
        opp.Shipping_State_Province__c = 'IL';
        opp.Shipping_Zip__c = '99999';        
        opp.Impact_Partner_Id__c = '1111';
        insert opp;               
        
    }

    @isTest
    private static void testPartnerHelperException(){
        PartnerException pe = new PartnerException();
        PartnerHelper ph = new PartnerHelper();
    }

    @isTest
    private static void testImpactCall() {

        MultiStaticResourceCalloutMock multimock = new MultiStaticResourceCalloutMock();
        multimock.setStaticResource('callout:ImpactLogConversionData', 'ImpactConversionResponseSuccess');
        multimock.setStatusCode(200);        

        Test.setMock(HttpCalloutMock.class, multimock);        

        // Create Payment Plan and Storage
        fw1__Payment_Plan__c pp = new fw1__Payment_Plan__c(
            Name = 'Test PP - OTP',
            fw1__Schedule__c = 'Monthly',
            Number_of_Payments__c = 1
        );
        insert pp;

        Opportunity opp = [Select ID from Opportunity LIMIT 1];
        //opp.Enrollment_Flow_Complete__c = true;
        opp.Payment_Plans__c = null;
        opp.fw2__Payment_Plan__c = pp.id;
        opp.fw1__Total_Paid_Amount__c=0;
        opp.Payment_Plans__c = 'OTP'; // added to go to production
        opp.Enrollment_Flow_Complete__c = true;
        opp.StageName = 'Enrolled';
        update opp;        
        
        fw1__Invoice__c cbo = [SELECT Id FROM fw1__Invoice__c LIMIT 1];      
        
        Test.startTest();
        
        cbo.Storage_Plan_Stored__c = 'LTS';
        cbo.Payment_Plan_Stored__c = 'OTP';
        cbo.fw1__Payment_Plan__c = pp.id;
        cbo.fw1__Auto_BillPay__c = true;
        update cbo;

        Test.stopTest();

        // Asserts
    }

    @isTest
    private static void testImpactCall_Explicit() {
        List<String> lstInvoiceIDs = new List<String>();
        List<List<String>> lstInvoiceIDs2 = new List<List<String>> ();


        MultiStaticResourceCalloutMock multimock = new MultiStaticResourceCalloutMock();
        multimock.setStaticResource('callout:ImpactLogConversionData', 'ImpactConversionResponseSuccess');
        multimock.setStatusCode(200);        

        Test.setMock(HttpCalloutMock.class, multimock);        

        // Create Payment Plan and Storage
        fw1__Payment_Plan__c pp = new fw1__Payment_Plan__c(
            Name = 'Test PP - OTP',
            fw1__Schedule__c = 'Monthly',
            Number_of_Payments__c = 1
        );
        insert pp;

        Opportunity opp = [Select ID from Opportunity LIMIT 1];
        //opp.Enrollment_Flow_Complete__c = true;
        opp.Payment_Plans__c = null;
        opp.fw2__Payment_Plan__c = pp.id;
        opp.fw1__Total_Paid_Amount__c=0;
        opp.Payment_Plans__c = 'OTP'; // added to go to production
        opp.Enrollment_Flow_Complete__c = true;
        opp.StageName = 'Enrolled';
        update opp;        
        
        fw1__Invoice__c cbo = [SELECT Id FROM fw1__Invoice__c LIMIT 1];      
        
        Test.startTest();
        
        cbo.Storage_Plan_Stored__c = 'LTS';
        cbo.Payment_Plan_Stored__c = 'OTP';
        cbo.fw1__Payment_Plan__c = pp.id;
        cbo.fw1__Auto_BillPay__c = true;
        update cbo;

        lstInvoiceIDs.add(cbo.Id);
        lstInvoiceIDs2.add(lstInvoiceIDs);

        PartnerConversion.sendConversionToImpact(lstInvoiceIDs2);

        Test.stopTest();

        // Asserts
    }    

}