force-app/main/default/objects/Americord_Docusign_Templates__mdt/Americord_Docusign_Templates__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata will store the Docusign templates that can be referenced by code and not hard-coded.</description>
    <label>Americord Docusign Template</label>
    <pluralLabel>Americord Docusign Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Americord_Docusign_Templates__mdt/fields/Docusign_Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Template_ID__c</fullName>
    <description>This is the template ID from docusign for the template.</description>
    <inlineHelpText>This is the template ID from docusign for the template.</inlineHelpText>
    <label>Docusign Template ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DocusignServices.cls
/**
* DocusignServices
* ------------------
* @author jseibert
*/
public with sharing class DocusignServices {
    /**
    * getCurrentIntegrationSettings
    * -------
    * returns the custom metadata values for use in by apex.
    */
    public static String getDocusignTemplateId(String strDocusignDoc){
        Americord_Docusign_Templates__mdt docusignTemplate = [
            SELECT 
            Docusign_Template_ID__c
            FROM Americord_Docusign_Templates__mdt 
            WHERE DeveloperName = :strDocusignDoc LIMIT 1];
            
            return docusignTemplate.Docusign_Template_ID__c;
    }    
}