force-app/main/default/objects/Americord_Docusign_Templates__mdt/Americord_Docusign_Templates__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata will store the Docusign templates that can be referenced by code and not hard-coded.</description>
    <label>Americord Docusign Template</label>
    <pluralLabel>Americord Docusign Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Americord_Docusign_Templates__mdt/fields/Docusign_Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Template_ID__c</fullName>
    <description>This is the template ID from docusign for the template.</description>
    <inlineHelpText>This is the template ID from docusign for the template.</inlineHelpText>
    <label>Docusign Template ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount_Code__mdt/Discount_Code__mdt.object-meta.xml
<CustomObject>
    <description>Stores the discount codes available on the EComm Site and their associated discount values</description>
    <label>Discount Code</label>
    <pluralLabel>Discount Codes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Discount_Code__mdt/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Total Dollar Amount to be discounted for this code.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount_Code__mdt/fields/Applicable_Bundles__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Bundles__c</fullName>
    <description>Comma separated list of the product codes for bundles that this discount code may be applied to.  If populated, this will ONLY be used for the specified bundles.</description>
    <label>Applicable Bundles</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount_Code__mdt/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Last day that this code is valid.</description>
    <inlineHelpText>Last day that this code is valid.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Discount_Code__mdt/fields/Price_Limit__c.field-meta.xml
<CustomField>
    <fullName>Price_Limit__c</fullName>
    <description>The minimum cart amount at which this discount code can be applied.</description>
    <inlineHelpText>The minimum cart amount at which this discount code can be applied.</inlineHelpText>
    <label>Price Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount_Code__mdt/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date upon which this code becomes valid.</description>
    <inlineHelpText>Date upon which this code becomes valid.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CustomMetadataServiceTest.cls
@isTest
public class CustomMetadataServiceTest {
    public static List<Americord_Docusign_Templates__mdt> lstDocusignTemplates = new List <Americord_Docusign_Templates__mdt>();
    public static List<Discount_Code__mdt> lstDiscountCodes = new List <Discount_Code__mdt>();

    @isTest
    static void testCMTNullDocsignTemplatesMeta() {
        Map<String,Americord_Docusign_Templates__mdt> mapDocuTempTest = new Map<String,Americord_Docusign_Templates__mdt>();
        List<Americord_Docusign_Templates__mdt> lstDocuTempTest = new List<Americord_Docusign_Templates__mdt>();

        CustomMetadataService.lstDocusignTemplates = null;
        lstDocuTempTest =  CustomMetadataService.getAllDocusignTemplates();        
        CustomMetadataService.lstDocusignTemplates = null;        
        mapDocuTempTest = CustomMetadataService.getMapDocusignTemplates();
    }    

    @isTest
    static void testCMTNullDiscountCodes() {
        Map<String,Discount_Code__mdt> mapDiscountCodesTest = new Map<String,Discount_Code__mdt>();
        List<Discount_Code__mdt> lstDiscCodesTest = new List<Discount_Code__mdt>();
        
        CustomMetadataService.lstDiscountCodes = null;
        lstDiscCodesTest = CustomMetadataService.getAllDiscountCodes();        
        CustomMetadataService.lstDiscountCodes = null;        
        mapDiscountCodesTest = CustomMetadataService.getMapDiscountCodes();
    }    

    @isTest
    static void testDocsignTemplatesMetaTest() {
        // Docusign Metadata
        Americord_Docusign_Templates__mdt docuTemplate = new Americord_Docusign_Templates__mdt();
        docuTemplate.Docusign_Template_ID__c = '12345';
        docuTemplate.Label = 'MHQ Template';
        docuTemplate.DeveloperName = 'MHQ_Template';
        lstDocusignTemplates.add(docuTemplate);

        List<Americord_Docusign_Templates__mdt> lstDocuTempTest = new List<Americord_Docusign_Templates__mdt>();
        Map<String,Americord_Docusign_Templates__mdt> mapDocuTempTest = new Map<String,Americord_Docusign_Templates__mdt>();
        CustomMetadataService.lstDocusignTemplates = lstDocusignTemplates;
        lstDocuTempTest =  CustomMetadataService.getAllDocusignTemplates();
        mapDocuTempTest = CustomMetadataService.getMapDocusignTemplates();
        System.assertEquals(1, lstDocuTempTest.size(), 'Number of returned documents is not correct.');
         
    }
    @isTest
    static void testDiscountCodesTest() {
        // Discount Codes
        Discount_Code__mdt discCode = new Discount_Code__mdt();
        discCode.Label = 'WTE400';
        discCode.DeveloperName = 'WTE400';
        discCode.Amount__c = 400;
        discCode.Price_Limit__c = 4000;
        discCode.Start_Date__c = System.today();
        discCode.End_Date__c = System.today()+7;
        discCode.Applicable_Bundles__c = 'Biobanking';
        lstDiscountCodes.add(discCode);

        List<Discount_Code__mdt> lstDiscCodesTest = new List<Discount_Code__mdt>();
        Map<String,Discount_Code__mdt> mapDiscountCodesTest = new Map<String,Discount_Code__mdt>();
        CustomMetadataService.lstDiscountCodes = lstDiscountCodes;
        lstDiscCodesTest = CustomMetadataService.getAllDiscountCodes();
        mapDiscountCodesTest = CustomMetadataService.getMapDiscountCodes();
        System.assertEquals(1, lstDiscCodesTest.size(), 'Number of returned discount codes is not correct.');        
    }

}