force-app/main/default/objects/Americord_Docusign_Templates__mdt/Americord_Docusign_Templates__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata will store the Docusign templates that can be referenced by code and not hard-coded.</description>
    <label>Americord Docusign Template</label>
    <pluralLabel>Americord Docusign Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Americord_Docusign_Templates__mdt/fields/Docusign_Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Template_ID__c</fullName>
    <description>This is the template ID from docusign for the template.</description>
    <inlineHelpText>This is the template ID from docusign for the template.</inlineHelpText>
    <label>Docusign Template ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MHQ__c/MHQ__c.object-meta.xml
<CustomObject>
    <label>MHQ</label>
    <nameField>
        <displayFormat>MHQ-{0000}</displayFormat>
        <label>MHQ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MHQs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MHQ__c/fields/MHQ_Recipient__c.field-meta.xml
<CustomField>
    <fullName>MHQ_Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to the contact for the MHQ Recipient.</description>
    <inlineHelpText>This is a lookup to the contact for the MHQ Recipient.</inlineHelpText>
    <label>MHQ Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MHQs</relationshipLabel>
    <relationshipName>MHQs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DocusignServicesTest.cls
@isTest
/**
* DocusignServicesTest
* ------------------
* @author jseibert
*/
private class DocusignServicesTest {
    @testSetup static void setup() {
        AmericordTestDataFactory testData = new AmericordTestDataFactory ();   
        
        Contact testContact = new Contact();
        testContact.FirstName ='Testor';
        testContact.LastName = 'Lastname';
        testContact.Email = 'testor@someco.com';
        insert testContact;

        MHQ__c testMHQ = new MHQ__c();
        testMHQ.MHQ_Recipient__c = testContact.Id;
        insert testMHQ;

        List<Americord_Docusign_Templates__mdt> docusignTemplates = setDocusignTemplates();
        
    }      
    private static List<Americord_Docusign_Templates__mdt> setDocusignTemplates () {
    	
        List < Americord_Docusign_Templates__mdt > lstDocusignTemplates = new List <Americord_Docusign_Templates__mdt>();

        Americord_Docusign_Templates__mdt testTemplate = new Americord_Docusign_Templates__mdt();
        testTemplate.label = 'MHQ Template';
        testTemplate.developerName = 'MHQ_Template';
        testTemplate.Docusign_Template_ID__c = 'abc123';
        lstDocusignTemplates.add(testTemplate);

        CustomMetadataService.lstDocusignTemplates = lstDocusignTemplates;
        lstDocusignTemplates = CustomMetadataService.getAllDocusignTemplates(); //coverage
        return lstDocusignTemplates;
    }    

    @isTest
    private static void testSendingMHQ() {        

        Test.startTest();
        String strTest = DocusignServices.getDocusignTemplateId('MHQ_Template');
        Test.stopTest();

        System.assertNotEquals(null, strTest, 'Template ID returned from getDocusignTemplateID incorrect:'+strTest);

        //asserts
    }


}