force-app/main/default/objects/Lab__c/Lab__c.object-meta.xml
<CustomObject>
    <label>Lab</label>
    <nameField>
        <label>Lab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Labs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab__c/fields/Cord_Blood_2_0_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Cord_Blood_2_0_Ordered__c</fullName>
    <formula>Cord_Blood_Order__r.Cord_Blood_2_0_Ordered__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZDeprecate Cord Blood 2.0 Ordered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Cord_Blood_2_0_Stored__c.field-meta.xml
<CustomField>
    <fullName>Cord_Blood_2_0_Stored__c</fullName>
    <label>Cord Blood 2.0 Stored</label>
    <summaryFilterItems>
        <field>Baby__c.Cord_Blood_Cryogenically_Preserved__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Baby__c.Lab__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Cord_Blood_Collection_Completed__c.field-meta.xml
<CustomField>
    <fullName>Cord_Blood_Collection_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The AirNet or Medical Courier confirmation was received. Stem cells were collected and delivered to the lab.</description>
    <label>Courier P/U</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Cord_Tissue_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Cord_Tissue_Ordered__c</fullName>
    <formula>Cord_Blood_Order__r.Cord_Tissue_Ordered__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZDeprecate Cord Tissue Ordered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Cord_Tissue_Stored__c.field-meta.xml
<CustomField>
    <fullName>Cord_Tissue_Stored__c</fullName>
    <label>Cord Tissue Stored</label>
    <summaryFilterItems>
        <field>Baby__c.Cord_Tissue_Cryogenically_Preserved__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Baby__c.Lab__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Labs</relationshipLabel>
    <relationshipName>Labs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Payment_Plan_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan_Ordered__c</fullName>
    <formula>TEXT(Cord_Blood_Order__r.Payment_Plan_Ordered__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Plan Ordered</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Payment_Plan_Stored__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan_Stored__c</fullName>
    <description>Used for Docusign when client signs after baby is born.</description>
    <formula>Text(Cord_Blood_Order__r.Payment_Plan_Stored__c)</formula>
    <label>Payment Plan Stored</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Storage_Plan_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Storage_Plan_Ordered__c</fullName>
    <formula>TEXT(Cord_Blood_Order__r.Storage_Plan_Ordered__c)</formula>
    <label>Storage Plan Ordered</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Storage_Plan_Stored__c.field-meta.xml
<CustomField>
    <fullName>Storage_Plan_Stored__c</fullName>
    <description>Used for Docusign, when clients sign after baby is born.</description>
    <formula>Text(Cord_Blood_Order__r.Storage_Plan_Stored__c)</formula>
    <label>Storage Plan Stored</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Baby_s_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Baby_s_Due_Date__c</fullName>
    <label>Baby&apos;s Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ecomm_Status__c.field-meta.xml
<CustomField>
    <fullName>Ecomm_Status__c</fullName>
    <label>Ecomm Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Plans__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plans__c</fullName>
    <label>ZDEPRECATE_Payment Plans</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTP</fullName>
                <label>One-time Payment</label>
            </value>
            <value>
                <fullName>24M</fullName>
                <label>24 Months</label>
            </value>
            <value>
                <fullName>36M</fullName>
                <label>36 Months</label>
            </value>
            <value>
                <fullName>48M</fullName>
                <label>48 Months</label>
            </value>
            <value>
                <fullName>HY18</fullName>
                <label>Hybrid - 18</label>
            </value>
            <value>
                <fullName>12M</fullName>
                <label>12 Months</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pricing_Version__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Version__c</fullName>
    <description>Corresponds with the pricing API version.</description>
    <label>Pricing Version</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Storage_Plan__c.field-meta.xml
<CustomField>
    <fullName>Storage_Plan__c</fullName>
    <label>Storage Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Storage</fullName>
            </value>
            <value>
                <fullName>20YPP</fullName>
                <label>20 Years Prepaid</label>
            </value>
            <value>
                <fullName>ASP</fullName>
                <label>Annual Storage</label>
            </value>
            <value>
                <fullName>LTS</fullName>
                <label>Lifetime Storage</label>
            </value>
            <value>
                <fullName>Donated</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Pricing_Version__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Version__c</fullName>
    <description>Optional, indicates the Pricing Version that uses this pricebook.  Versions are used by the website to provide different base pricing to web visitors.</description>
    <inlineHelpText>Optional, indicates the Pricing Version that uses this pricebook.  Versions are used by the website to provide different base pricing to web visitors.</inlineHelpText>
    <label>Pricing Version</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Version__mdt/Pricing_Version__mdt.object-meta.xml
<CustomObject>
    <description>Stores data about product pricing and data associated with the new (2021) web purchasing process.</description>
    <label>Pricing Version</label>
    <pluralLabel>Pricing Versions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pricing_Version__mdt/fields/Is_Default__c.field-meta.xml
<CustomField>
    <fullName>Is_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if this is the default Pricing Version for the website.</description>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pricing_Version__mdt/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>The annual interest rate to apply to financed purchases with this version.</description>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Pricing_Version__mdt/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <description>The version number.</description>
    <label>Version Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SliderCalculatorTest.cls
@isTest
private class SliderCalculatorTest {
    
    // @TestSetup
    // static void makeData(){

    //     //create flex pricebook
    //     Pricebook2 pbFlex = new Pricebook2(
    //         Name='Ameriflex 1.0',
    //         Pricing_Version__c = 1.0,
    //         IsActive=true
    //     );
    //     insert pbFlex;

    //     //Create default pricebook structures
    //     AmericordTestDataFactory testFactory = new AmericordTestDataFactory();

    //     List < Product2 > allProducts = [SELECT ID, ProductCode FROM Product2];

    //     Map < string, sObject > productMap = Toolkit.indexedSObjectMap ( allProducts, 'ProductCode' );        

    //     // Create Pricebook Entries
    //     List < PricebookEntry > pricebookEntriesForInsert = new List < PricebookEntry > ();

    //     PricebookEntry standardPrice = new PricebookEntry (Pricebook2Id = pbFlex.Id, 
    //                                                        Product2Id = (Id) productMap.get ( 'CB2.0' ).get ( 'Id' ),
    //                                                        UnitPrice = 1499, 
    //                                                        IsActive = true);
    //     pricebookEntriesForInsert.add ( standardPrice );

    //     standardPrice = new PricebookEntry (Pricebook2Id = pbFlex.Id, 
    //                         Product2Id = (Id) productMap.get ( 'CT' ).get ( 'Id' ),
    //                         UnitPrice = 1499, 
    //                         IsActive = true);
        
    //     pricebookEntriesForInsert.add ( standardPrice );

    //     standardPrice = new PricebookEntry (Pricebook2Id = pbFlex.Id, 
    //                         Product2Id = (Id) productMap.get ( 'PAM' ).get ( 'Id' ),
    //                         UnitPrice = 1499, 
    //                         IsActive = true);
        
    //     pricebookEntriesForInsert.add ( standardPrice );
        
        				
    //     standardPrice = new PricebookEntry (Pricebook2Id = pbFlex.Id, 
    //                         Product2Id = (Id) productMap.get ( '20YPP' ).get ( 'Id' ),
    //                         UnitPrice = 2000, 
    //                         IsActive = true);
        
    //     pricebookEntriesForInsert.add ( standardPrice );
    
        
    //     standardPrice = new PricebookEntry (Pricebook2Id = pbFlex.Id, 
    //                                         Product2Id = (Id) productMap.get ( 'LTS' ).get ( 'Id' ),
    //                                         UnitPrice = 4250, 
    //                                         IsActive = true);
        
    //     pricebookEntriesForInsert.add ( standardPrice );

    //     insert pricebookEntriesForInsert;
        

    // }

    // @isTest
    // static void loadPricingTest() {
    //     //20 Year
    //     String jsonMap20Yr = SliderCalculatorController.loadPricingMap('20YPP');

    //     SliderPricing twentyYearPricing = (SliderPricing) JSON.deserialize(jsonMap20Yr, SliderPricing.class);

    //     System.debug('twentyYearPricing: '+JSON.serialize(twentyYearPricing));

    //     Map < Decimal, Decimal > twentyYrInnerMap = twentyYearPricing.paymentMap.get(6);

    //     //Validate we get an amount back for 6 months and $100 downpayment and 20 year storage
    //     System.assertNotEquals(null, twentyYrInnerMap.get(100));

    //     //Lifetime
    //     String jsonMapLifetime = SliderCalculatorController.loadPricingMap('LTS');
    //     SliderPricing lifetimeStoragePricing = (SliderPricing) JSON.deserialize(jsonMapLifetime, SliderPricing.class);


    //     Map < Decimal, Decimal > ltsInnerMap = lifetimeStoragePricing.paymentMap.get(6);

    //     //Validate we get an amount back for 6 months and $100 downpayment and 20 year storage
    //     System.assertNotEquals(null, ltsInnerMap.get(100));

    //     //Validate that LTS and 20 year give different values
    //     System.assertNotEquals(twentyYrInnerMap.get(100), ltsInnerMap.get(100));

    // }

    // @isTest
    // static void testMetadataMethods() {
    //     //Get the rate for 1.0 from metadata
    //     Double rate;
    //     Decimal defaultVersion;
    //     Map<String, Pricing_Version__mdt> pricingMetadata = Pricing_Version__mdt.getAll();
    //     for (Pricing_Version__mdt ver: pricingMetadata.values()) {
    //         if (ver.Version_Number__c==1.0) {
    //             rate = ver.Rate__c;
    //         }
    //         if (ver.Is_Default__c) {
    //             defaultVersion = ver.Version_Number__c;
    //         }
    //     }

    //     Double fetchedRate = SliderCalculatorController.getRate(1.0);
    //     System.assertEquals(rate, fetchedRate);

    //     Decimal fetchedDefault = SliderCalculatorController.getDefaultVersion();
    //     System.assertEquals(defaultVersion, fetchedDefault);
    // }

    // @isTest
    // static Void pricebookMethodTests() {
    //     //Query the 1.0 pricebook
    //     Pricebook2 pbWithVersion = [SELECT ID, Name FROM Pricebook2 WHERE Pricing_Version__c=1.0];
    //     Pricebook2 pbWithoutVersion = [SELECT ID, Name FROM Pricebook2 WHERE Pricing_Version__c=null LIMIT 1];

    //     System.assertEquals(true, SliderCalculatorController.pricebookIsVersioned(pbWithVersion.Id));
    //     System.assertEquals(false, SliderCalculatorController.pricebookIsVersioned(pbWithoutVersion.Id));

    //     Pricebook2 pbFetched = SliderCalculatorController.getPricebookWithEntries(1.0);
    //     System.assertEquals(pbWithVersion.Id, pbFetched.Id);

    // }

    // @isTest
    // static Void oppUpdateTests() {

    //     //Create an Opportunity
    //     Opportunity opp = AmericordTestDataFactory.createOpportunity('Test Flex Opp', 'New', true);

    //     SliderCalculatorController.updateOpportunity('20YPP', 6, 1000, 0, opp.Id);

    //     Opportunity updatedOpp = [SELECT ID, Pricing_Version__c, Payment_Plans__c FROM Opportunity WHERE ID=:opp.Id];

    //     Decimal defaultPricebookVersion = SliderCalculatorController.getDefaultVersion();
        
    //     //Validate the opportunity is now using the default pricebook
    //     System.assertEquals(defaultPricebookVersion, updatedOpp.Pricing_Version__c);

    //     //Now we'll close out the opportunity so that a CBO is generated
    //     opp.StageName = 'Enrolled';
    //     update opp;

    //     //Get the Labs and mark them as collected
    //     Lab__c lab = [SELECT ID FROM Lab__c WHERE Opportunity__c=:opp.Id];
    //     lab.Cord_Blood_Collection_Completed__c = true;
    //     update lab;

    //     //Update the invoice
    //     fw1__Invoice__c inv = [SELECT ID, Cord_Blood_2_0_Ordered__c, Cord_Tissue_Ordered__c, Placenta_2_0_Ordered__c, Storage_Plan_Ordered__c, Payment_Plan_Ordered__c FROM fw1__Invoice__c WHERE fw1__Opportunity__c=:opp.Id];

    //     System.debug('inv should have 6 month flex: '+inv);
    //     inv.Payment_Plan_Ordered__c = 'FLEX6';
    //     inv.Cord_Blood_2_0_Stored__c = inv.Cord_Blood_2_0_Ordered__c;
    //     inv.Cord_Tissue_Stored__c = inv.Cord_Tissue_Ordered__c;
    //     inv.Placenta_2_0_Stored__c = inv.Placenta_2_0_Ordered__c;
    //     inv.Storage_Plan_Stored__c = inv.Storage_Plan_Ordered__c;
    //     inv.Payment_Plan_Stored__c = inv.Payment_Plan_Ordered__c;
    //     update inv;

    //     inv.fw1__Auto_BillPay__c = true;
    //     update inv;

    // }

    // @isTest
    // static Void oppOTPTests() {

    //     //Create an Opportunity
    //     Opportunity opp = AmericordTestDataFactory.createOpportunity('Test Flex Opp', 'New', true);

    //     //Now do lifetime and OTP
    //     SliderCalculatorController.updateOpportunity('LTS', 0, 1000, 0, opp.Id);
    //     Opportunity updatedOppLifetime = [SELECT ID, Storage_Plan__c, Payment_Plans__c FROM Opportunity WHERE ID=:opp.Id];
    //     System.assertEquals('LTS', updatedOppLifetime.Storage_Plan__c);
    //     System.assertEquals('OTP', updatedOppLifetime.Payment_Plans__c);

    //     //Now we'll close out the opportunity so that a CBO is generated
    //     opp.StageName = 'Enrolled';
    //     update opp;

    // }

    // @isTest
    // static Void webGiftTest() {

    //     //Create an Opportunity
    //     Opportunity opp = AmericordTestDataFactory.createOpportunity('Test Flex Opp', 'New', false);

    //     //set it up as an incoming web gift
    //     opp.Ecomm_Status__c = 'Enrolled';
    //     opp.Pricing_Version__c = 1.0;
    //     opp.CloseDate = System.today();
    //     opp.Baby_s_Due_Date__c = System.today().addDays(1);

    //     insert opp;

    //     System.debug('web opp: '+opp);
        

    // }

}