force-app/main/default/objects/Lead/fields/Agreement_Escalation__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Escalation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check when Holly needs to contact client to get a signed agreement.</description>
    <label>Agreement Escalation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Alt_Email__c.field-meta.xml
<CustomField>
    <fullName>Alt_Email__c</fullName>
    <label>Parent 2 Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Alt_Phone__c.field-meta.xml
<CustomField>
    <fullName>Alt_Phone__c</fullName>
    <label>Parent 2 Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Authorization_ID__c.field-meta.xml
<CustomField>
    <fullName>Authorization_ID__c</fullName>
    <label>Authorization ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Babys_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Babys_Due_Date__c</fullName>
    <label>Baby&apos;s Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Billing_Address1__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address1__c</fullName>
    <label>Billing Address1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Billing_Address2__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address2__c</fullName>
    <label>Billing Address2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <label>Billing State</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Billing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Code__c</fullName>
    <label>Billing Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CC_Call_1__c.field-meta.xml
<CustomField>
    <fullName>CC_Call_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CC Call 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CC_Call_2__c.field-meta.xml
<CustomField>
    <fullName>CC_Call_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CC Call 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CC_Email_1__c.field-meta.xml
<CustomField>
    <fullName>CC_Email_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CC Email 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CC_Email_2__c.field-meta.xml
<CustomField>
    <fullName>CC_Email_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CC Email 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Client_Billed__c.field-meta.xml
<CustomField>
    <fullName>Client_Billed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Collection sheet matches enrollment option and successfully billed client?</description>
    <label>Billed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Coupon_Code__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Code__c</fullName>
    <label>Coupon Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Enrolled_by_email__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_by_email__c</fullName>
    <label>Enrolled by email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Enrolled_by_first_name__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_by_first_name__c</fullName>
    <description>The person who completed the initial online enrollment form.</description>
    <label>Enrolled by first name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Enrolled_by_last_name__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_by_last_name__c</fullName>
    <label>Enrolled by last name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Enrolled_by_phone__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_by_phone__c</fullName>
    <label>Enrolled by phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Father_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Father_s_Name__c</fullName>
    <label>Parent 2 Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Follow_up_Subject__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Subject__c</fullName>
    <label>Follow-up Subject</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Calling back for credit card</fullName>
            </value>
            <value>
                <fullName>Need to talk to husband</fullName>
            </value>
            <value>
                <fullName>Second trimester follow-up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Hospital_Name__c.field-meta.xml
<CustomField>
    <fullName>Hospital_Name__c</fullName>
    <label>Hospital Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/how_did_you_learn_about_americord__c.field-meta.xml
<CustomField>
    <fullName>how_did_you_learn_about_americord__c</fullName>
    <description>Populated from Info Kit text box.</description>
    <label>How did you learn about Americord?</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/OBGYN_Name__c.field-meta.xml
<CustomField>
    <fullName>OBGYN_Name__c</fullName>
    <label>OBGYN Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product1__c.field-meta.xml
<CustomField>
    <fullName>Product1__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cord Blood 2.0 (one-time payment - single child)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 (24 month - single child)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue (one-time payment - single child)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue (24 month - single child)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Placenta Tissue (one-time payment - single child)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Placenta Tissue (24 month - single child)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue &amp; Placenta Tissue (one-time payment - single child)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue &amp; Placenta Tissue (24 month - single child)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 (one-time payment - twins)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 (24 month - twins)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue (one-time payment - twins)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue (24 month - twins)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Placenta Tissue (one-time payment - twins)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Placenta Tissue (24 month - twins)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue &amp; Placenta Tissue (one-time payment - twins)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue &amp; Placenta Tissue (24 month - twins)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 (one-time payment - triplets)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 (24 month - triplets)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue (one-time payment - triplets)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue (24 month - triplets)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Placenta Tissue (one-time payment - triplets)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Placenta Tissue (24 month - triplets)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue &amp; Placenta Tissue (one-time payment - triplets)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue &amp; Placenta Tissue (24 month - triplets)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 (12 month - single child)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue (12 month - single child)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Placenta Tissue (12 month - single child)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue &amp; Placenta Tissue (12 month - single child)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue plus Placenta Tissue for one (one-time payment - twins)</fullName>
            </value>
            <value>
                <fullName>Cord Blood 2.0 with Cord Tissue plus Placenta Tissue for one (24 month - twins)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_Discount_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Product_Discount_Amount1__c</fullName>
    <label>Product Discount Amount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_List_Price1__c.field-meta.xml
<CustomField>
    <fullName>Product_List_Price1__c</fullName>
    <label>Product List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referrer_Email__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Email__c</fullName>
    <label>Referred by Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referrer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_First_Name__c</fullName>
    <label>Referred by First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referrer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Last_Name__c</fullName>
    <label>Referred by Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/relation__c.field-meta.xml
<CustomField>
    <fullName>relation__c</fullName>
    <description>What is your relationship to the baby?</description>
    <inlineHelpText>What is your relationship to the baby?</inlineHelpText>
    <label>Parent 2 Relation to baby</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Rep_Follow_up__c.field-meta.xml
<CustomField>
    <fullName>Rep_Follow_up__c</fullName>
    <label>Rep Follow-up</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ayanna</fullName>
            </value>
            <value>
                <fullName>Gail</fullName>
            </value>
            <value>
                <fullName>Jas</fullName>
            </value>
            <value>
                <fullName>Jerry</fullName>
            </value>
            <value>
                <fullName>Michael</fullName>
            </value>
            <value>
                <fullName>Paula</fullName>
            </value>
            <value>
                <fullName>John</fullName>
            </value>
            <value>
                <fullName>Simone</fullName>
            </value>
            <value>
                <fullName>MJ</fullName>
            </value>
            <value>
                <fullName>Devyn</fullName>
            </value>
            <value>
                <fullName>Simon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Returning_Client__c.field-meta.xml
<CustomField>
    <fullName>Returning_Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Returning Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Sent_Marketing_Email__c.field-meta.xml
<CustomField>
    <fullName>Sent_Marketing_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box to indicate that a marketing email was sent to the client.</inlineHelpText>
    <label>Email 1x</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Shipping_Notes__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Notes__c</fullName>
    <inlineHelpText>Provide special instructions for shipping, as required.</inlineHelpText>
    <label>Shipping Notes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadConversionSettings__c/LeadConversionSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Lead Conversion Settings</label>
</CustomObject>

force-app/main/default/objects/LeadConversionSettings__c/fields/Turn_On_Lead_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Turn_On_Lead_Conversion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Turn On Lead Conversion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ConvertLeadTests.cls
@isTest
public with sharing class ConvertLeadTests {

    /*static testMethod void testConvertLead() {
        // create custom setting
        LeadConversionSettings__c setting = new LeadConversionSettings__c();
        setting.Name = 'Test Setting';
        setting.Turn_On_Lead_Conversion__c = true;
        insert setting;
        
        // create settings
        fw1__Payment_Center_Setting__c s = new fw1__Payment_Center_Setting__c();
        s.Name = 'Default Settings';
        insert s;
        
        // create payment
        fw1__Payment__c p = new fw1__Payment__c();
        p.Name = 'test payment';
        p.fw1__Payment_Date__c = system.now();
        p.fw1__Amount__c = 1;
        p.fw1__Status__c = 'Voided';
        insert p;
        
        // create lead
        Lead l = new Lead();
        l.FirstName = 'Rena';
        l.LastName = 'Hughes';
        l.Company = 'Rena Hughes';
        l.Email = 'test@test.com';
        l.Phone = '1231234321';
        l.Babys_Due_Date__c = system.today();
        l.Father_s_Name__c = 'John Hughes';
        l.Authorization_ID__c = p.Id;
        l.Product1__c = 'Cord Blood 24 month';
        l.Product_List_Price1__c = 800;
        l.Product_Discount_Amount1__c = 200;
        l.Coupon_Code__c = 'ddd';
        l.Hospital_Name__c = 'Cumberland Medical Center';
        l.OBGYN_Name__c = 'Kimberly Johnson';
        l.Returning_Client__c = true;
        l.Referrer_First_Name__c = 'Tina';
        l.Referrer_Last_Name__c = 'Smith';
        l.Referrer_Email__c = 'test3@test3.com';
        l.Follow_up_Subject__c = 'Calling back for credit card';
        l.Rep_Follow_up__c = 'Martin';
        l.Returning_Client__c = true;
        l.Alt_Email__c = 'test4@test4.com';
        l.Alt_Phone__c = '2345678909';
        l.Enrolled_by_email__c = 'test5@test5.com';
        l.Enrolled_by_first_name__c = 'Amanda';
        l.Enrolled_by_last_name__c = 'Jones';
        l.Enrolled_by_phone__c = '3456789098';
        l.relation__c = 'Other';
        l.CC_Call_1__c = false;
        l.CC_Call_2__c = false;
        l.CC_Email_1__c = false;
        l.CC_Email_2__c = false;
        l.Sent_Marketing_Email__c = true;
        l.Email_1x__c = true;
        l.How_did_you_find_us__c = 'sample';
        l.how_did_you_learn_about_americord__c = 'sample';
        l.Shipping_Notes__c = 'sample';
        l.Agreement_Escalation__c = false;
        l.Client_Billed__c = false;
        l.Billing_Address1__c = '1 Main Street';
        l.Billing_Address2__c = 'Apt 2B';
        l.Billing_City__c = 'Anywhere';
        l.Billing_State__c = 'Alaska';
        l.Billing_Zip_Code__c = '11111';
        l.Billing_Notes__c = 'sample';
        l.Billing_Notes_Needs_Review__c = false;
        l.Called_Prospect__c = false;
        l.Called_2x__c = false;
        l.Called_3x__c = false;
        l.Cancellation_Comments__c = 'sample';
        l.CC_Comments_1__c = 'sample';
        l.CC_Comments_2__c = 'sample';
        l.Client_Responded__c = false;
        l.OBGYN_Practice_Name__c = 'My OBGYN';
        l.Hospital_Phone__c = '222-222-2222';
        l.OBGYN_Phone__c = '333-333-3333';
        l.smagicinteract__SMSOptOut__c = true;
        insert l;
        
        l.Status = 'Enrolled';
        Test.startTest();
            update l;
        Test.stopTest();
    }*/
}