force-app/main/default/objects/Opportunity/fields/Cord_Blood_2_0__c.field-meta.xml
<CustomField>
    <fullName>Cord_Blood_2_0__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ZDeprecate Cord Blood 2.0</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cord_Tissue__c.field-meta.xml
<CustomField>
    <fullName>Cord_Tissue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ZDeprecate Cord Tissue</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Coupon_Code__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Code__c</fullName>
    <label>Coupon Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <defaultValue>199</defaultValue>
    <description>Used to populate a default value so formula fields are correct when calculating amount due and monthly payments. This field can be used to change the deposit value in the future. It can also be used to remove the deposit, if an exception is made for a client with no deposit.</description>
    <label>Deposit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Exosomes__c.field-meta.xml
<CustomField>
    <fullName>Exosomes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ZDeprecate Exosomes</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maternal_Exosomes__c.field-meta.xml
<CustomField>
    <fullName>Maternal_Exosomes__c</fullName>
    <description>Number indicating the order for maternal exosomes.</description>
    <label>Maternal Exosomes</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/My_Genome_Premium__c.field-meta.xml
<CustomField>
    <fullName>My_Genome_Premium__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ZDeprecate My Genome Premium</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/My_Genome_Standard__c.field-meta.xml
<CustomField>
    <fullName>My_Genome_Standard__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ZDeprecate My Genome Standard</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Newborn_Genome__c.field-meta.xml
<CustomField>
    <fullName>Newborn_Genome__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ZDeprecate Newborn Genome</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Newborn_Panel__c.field-meta.xml
<CustomField>
    <fullName>Newborn_Panel__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Newborn Panel</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Numeric_Births__c.field-meta.xml
<CustomField>
    <fullName>Numeric_Births__c</fullName>
    <formula>if (ISPICKVAL(Number_of_Births__c, &quot;Single&quot;), 1,
if (ISPICKVAL(Number_of_Births__c, &quot;Twins&quot;), 2, 
if (ISPICKVAL(Number_of_Births__c, &quot;Triplets&quot;), 3,
0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used to create numeric value for number of births, used in Flow/Process Builder.</inlineHelpText>
    <label>Numeric Births</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Plans__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plans__c</fullName>
    <label>ZDEPRECATE_Payment Plans</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTP</fullName>
                <label>One-time Payment</label>
            </value>
            <value>
                <fullName>24M</fullName>
                <label>24 Months</label>
            </value>
            <value>
                <fullName>36M</fullName>
                <label>36 Months</label>
            </value>
            <value>
                <fullName>48M</fullName>
                <label>48 Months</label>
            </value>
            <value>
                <fullName>HY18</fullName>
                <label>Hybrid - 18</label>
            </value>
            <value>
                <fullName>12M</fullName>
                <label>12 Months</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Placenta_2_0__c.field-meta.xml
<CustomField>
    <fullName>Placenta_2_0__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ZDeprecate Placenta 2.0 (Amnion)</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pricing_Version__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Version__c</fullName>
    <description>Corresponds with the pricing API version.</description>
    <label>Pricing Version</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Discount__c.field-meta.xml
<CustomField>
    <fullName>Sales_Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sales Discount</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Type__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Type__c</fullName>
    <label>Shipping Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Rush</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Storage_Plan__c.field-meta.xml
<CustomField>
    <fullName>Storage_Plan__c</fullName>
    <label>Storage Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Storage</fullName>
            </value>
            <value>
                <fullName>20YPP</fullName>
                <label>20 Years Prepaid</label>
            </value>
            <value>
                <fullName>ASP</fullName>
                <label>Annual Storage</label>
            </value>
            <value>
                <fullName>LTS</fullName>
                <label>Lifetime Storage</label>
            </value>
            <value>
                <fullName>Donated</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Copies Family from Product onto Opportunity Line Item via Process Builder, used for Roll-up and Flow.</inlineHelpText>
    <label>Category</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Sales_Discount__c.field-meta.xml
<CustomField>
    <fullName>Sales_Discount__c</fullName>
    <description>Discretionary discount offered by Sales staff.</description>
    <inlineHelpText>Discretionary discount offered by Sales staff.</inlineHelpText>
    <label>Sales Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OpportunityLineItems.cls
public with sharing class OpportunityLineItems {
    private List<OpportunityLineItem> newOpptyLineItems = new List<OpportunityLineItem>();    
    private List<OpportunityLineItem> deleteOpptyLineItems = new List<OpportunityLineItem>();        
    private Set<Id> opptyIds = new Set<Id>();
    
    public void create(List<Opportunity> opptyList) {
        for (Opportunity op : opptyList) { 
            try {           
                OrderCalculator.Output output = OrderCalculator.calculate ( getCalcInput(op) );
                    System.debug('output: '+output);
                    if (output.lineItems.size() > 0) {                   
                        newOpptyLineItems.addAll(convertToOpptyLineItems(output.lineItems, op.Id, op.Pricebook2Id));
                    }
                    opptyIds.add(op.Id);                                  
                
            } catch (OrderCalculatorException oce ){
                op.addError(oce.userMessage);
            } catch (AuraHandledException ex) {
                op.addError(ex.getMessage());
            } 
            
        }

        deleteOpptyLineItems.addAll(getOpptyLineItems(opptyIds));

        System.debug('Size of delete list:'+deleteOpptyLineItems.size());
        if (deleteOpptyLineItems.size() > 0){
            for(OpportunityLineItem oli: deleteOpptyLineItems){
                System.debug('Deleting:'+oli.Name);
            }
            delete deleteOpptyLineItems;
        }
        
        if (newOpptyLineItems.size() > 0){
            insert newOpptyLineItems;
        }
        
        
        
    }
    
    public void updateOppty(List<Opportunity> opptyList) {
        for (Opportunity op : opptyList) { 
            try {                                                
                OrderCalculator.Output output = OrderCalculator.calculate ( getCalcInput(op) );                 
                op = output.convertToOpportunity (op);                 
            } catch (OrderCalculatorException oce ){
                op.addError(oce.userMessage);
            } catch (AuraHandledException ex) {
                op.addError(ex.getMessage());
            }          
        }
        update opptyList;
    }
    
    public static OrderCalculator.Input getCalcInput(Opportunity op) {
        OrderCalculator.Input input = new OrderCalculator.Input ();
        input.birthCount = integer.valueOf(op.Numeric_Births__c);
        input.cordBlood2Quantity = integer.valueOf(op.Cord_Blood_2_0__c);
        input.cordTissueQuantity = integer.valueOf(op.Cord_Tissue__c);
        input.placenta2Quantity = integer.valueOf(op.Placenta_2_0__c);

        input.exosomesQuantity = integer.valueOf(op.Exosomes__c);
        input.momPremiumGenomicsQuantity = integer.valueOf(op.My_Genome_Premium__c);
        input.momStandardGenomicsQuantity = integer.valueOf(op.My_Genome_Standard__c);
        input.newbornGenomeQuantity = integer.valueOf(op.Newborn_Genome__c);
        input.newbornPanelQuantity = integer.valueOf(op.Newborn_Panel__c);

        input.maternalExosomesQuantity = integer.valueOf(op.Maternal_Exosomes__c);

        input.priceBookId = op.Pricebook2Id;
        input.paymentPlan = op.Payment_Plans__c;
        input.storagePlan = op.Storage_Plan__c;
        input.discountCode = op.Coupon_Code__c;
        input.salesDiscount = op.Sales_Discount__c;
        input.depositAmount = op.Deposit__c;
        input.pricingVersion = op.Pricing_Version__c;
        input.shippingType = op.Shipping_Type__c;
        return input;
    }
    
    
    private List<OpportunityLineItem> convertToOpptyLineItems(List<OrderCalculator.LineItem> lineItems, id opptyId, id priceBookId) {
		List<OpportunityLineItem> opptyLineItems = new List<OpportunityLineItem>();
        for (OrderCalculator.LineItem li : lineItems) {

            System.debug('adding opp line items:'+li.productName+' '+li.productCode);
            
            OpportunityLineItem opli = new OpportunityLineItem();            
            opli.OpportunityId = opptyId;
            opli.Product2Id = li.productId;
            opli.Price_Book__c = priceBookId;
            opli.Product_Code__c = li.productCode;        
            opli.Category__c = li.category;
            opli.Quantity = li.quantity;                        
            opli.ServiceDate = Date.today();       
            opli.TotalPrice = (li.unitPrice * li.quantity).round(System.RoundingMode.HALF_UP); 
            opptyLineItems.add(opli);
        }
		return opptyLineItems;        
    }
	
    private List<OpportunityLineItem> getOpptyLineItems(Set<Id> opptyIds) {

        List<OpportunityLineItem> opptyLineItems = new List<OpportunityLineItem>();
        opptyLineItems = [
            SELECT Id,Name,Category__c,Price_Book__c,TotalPrice,UnitPrice,Product_Code__c,Quantity,Product2Id,OpportunityId
            FROM OpportunityLineItem
            WHERE OpportunityId IN :opptyIds];
        
		return opptyLineItems;         
    }

}