force-app/main/default/objects/Contact/fields/Portal_Authentication__c.field-meta.xml
<CustomField>
    <fullName>Portal_Authentication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portal Authentication</label>
    <referenceTo>Portal_Authentication__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portal_Authentication__c/Portal_Authentication__c.object-meta.xml
<CustomObject>
    <label>Portal Authentication</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Portal Authentication Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Authentications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portal_Authentication__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Authentication__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Username</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ResetPasswordTest.cls
@isTest
private class ResetPasswordTest
{
    @testSetup
    static void dataSetup()
    {
        Portal_Authentication__c portalAuthentication = new Portal_Authentication__c();
        portalAuthentication.Username__c = 'test@test.com';
        portalAuthentication.Password__c = 'test123!';
        insert portalAuthentication;

        Contact contact = new Contact();
        contact.FirstName = 'Test';
        contact.LastName = 'User';
        contact.Portal_Authentication__c = portalAuthentication.Id;
        insert contact;
    }

    static testMethod void positiveTest()
    {
        Contact contact = [SELECT Id FROM Contact];
        system.assert(contact.Id != null);

        Portal_Authentication__c portalAuthentication = [SELECT Id FROM Portal_Authentication__c];
        system.assert(portalAuthentication.Id != null);

        ws_ResetPassword.handlePost(portalAuthentication.Id, contact.Id);
    }
}