force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Role (Relation to Child)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Surrogate</fullName>
            </value>
            <value>
                <fullName>Egg Donor</fullName>
            </value>
            <value>
                <fullName>Sperm Donor</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Midwife</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>Receptionist</fullName>
            </value>
            <value>
                <fullName>Medical Assistant</fullName>
            </value>
            <value>
                <fullName>Physician Assistant</fullName>
            </value>
            <value>
                <fullName>Pregnancy Coordinator</fullName>
            </value>
            <value>
                <fullName>Practice Manager</fullName>
            </value>
            <value>
                <fullName>APRN</fullName>
            </value>
            <value>
                <fullName>Doula</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Surrogate Liaison</fullName>
            </value>
            <value>
                <fullName>Ambassador</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lab__c/Lab__c.object-meta.xml
<CustomObject>
    <label>Lab</label>
    <nameField>
        <label>Lab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Labs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lab__c/fields/Cord_Blood_Order__c.field-meta.xml
<CustomField>
    <fullName>Cord_Blood_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cord Blood Order</label>
    <referenceTo>fw1__Invoice__c</referenceTo>
    <relationshipLabel>Labs</relationshipLabel>
    <relationshipName>Labs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Father_s_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Father_s_First_Name__c</fullName>
    <inlineHelpText>Syncs with Contact info using a trigger</inlineHelpText>
    <label>Contact 2 First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lab__c/fields/Mother_s_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_First_Name__c</fullName>
    <inlineHelpText>Syncs with Contact info using a trigger</inlineHelpText>
    <label>Contact First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/updateContactDetailsTest.cls
@isTest(SeeAllData=true)
private class updateContactDetailsTest { /*
    @isTest static void TestContactDetails() {
        Account acc = new Account(name = 'Nilesh',AccountNumber='123456');
        insert acc;
        //Inserting contact
        Contact cont1 = new Contact(AccountId=acc.Id,FirstName='Nilesh',LastName='Borse',Phone='8888454455',Type__c = 'Father');
        Contact cont2 = new Contact(AccountId=acc.Id,FirstName='Nilesh',LastName='Borse',Phone='8888454455',Type__c = 'Mother');
        insert cont1;
        insert cont2;
        //Insert Invoice
       fw1__Invoice__c invoice = new fw1__Invoice__c(fw1__Account__c = acc.Id,fw1__Contact__c =cont2.Id);
       insert invoice;
        checkRecursion.isRec = false;
        //Insert lab 
        Lab__c lab = new Lab__c(Cord_Blood_Order__c=invoice.Id,Name='Test Lab');
        insert lab;
        checkRecursion.isRec = false;
        //System.debug('======Record ID-========'+lab.id);
        Lab__c lc = new Lab__c();
        lc.id = lab.id;
        lc.Father_s_First_Name__c = 'Test2';
        lc.Mother_s_First_Name__c = 'Tests';
        update lc;
        
        
        //checkRecursion.isRec = false;
        Account acc1 = new Account(name = 'Nilesh',AccountNumber='123456');
        insert acc1;
        //Inserting contact
        List<Contact> contList = new List<Contact>();
        /*Contact cont3 = new Contact(AccountId=acc1.Id,FirstName='Nilesh',LastName='Borse',Phone='8888454455',Type__c = 'Father');
        insert cont3;
        Contact cont4 = new Contact(AccountId=acc1.Id,FirstName='Nilesh',LastName='Borse',Phone='8888454455',Type__c = 'Mother');
        insert cont4;
        contList.add(new Contact(AccountId=acc1.Id,FirstName='Nilesh',LastName='Borse',Phone='8888454455',Type__c = 'Father'));
        contList.add(new Contact(AccountId=acc1.Id,FirstName='Nilesh',LastName='Borse',Phone='8888454455',Type__c = 'Mother'));
        insert contList;

        //Insert Invoice
       fw1__Invoice__c invoice1 = new fw1__Invoice__c(fw1__Account__c = acc1.Id,fw1__Contact__c = contList[0].Id);
       insert invoice1;
       //checkRecursion.isRec = false;
        //Insert lab 
        Lab__c lab1 = new Lab__c(Cord_Blood_Order__c=invoice1.Id,Name='Test Lab');
        insert lab1;
        checkRecursion.isRec = false;
        Contact con1 = new Contact();
        con1.id = contList[0].id;
        //con1.AccountId = acc1.id;
        con1.FirstName = 'Nil1';
        update con1;
        
    } */
}