force-app/main/default/objects/Applied_Bundle__c/Applied_Bundle__c.object-meta.xml
<CustomObject>
    <description>Joins bundles to Opportunities</description>
    <label>Applied Bundle</label>
    <nameField>
        <displayFormat>AB-{000000}</displayFormat>
        <label>Applied Bundle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applied Bundle</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applied_Bundle__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <label>Bundle</label>
    <referenceTo>Bundle__c</referenceTo>
    <relationshipLabel>Applied Bundle</relationshipLabel>
    <relationshipName>Applied_Bundle</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applied_Bundle__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>fw1__Invoice__c</referenceTo>
    <relationshipLabel>Applied Bundle</relationshipLabel>
    <relationshipName>Applied_Bundles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applied_Bundle__c/fields/Marketing_Discount__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Discount__c</fullName>
    <description>A discount that was added via a promotional code or similar.</description>
    <label>Marketing Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applied_Bundle__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applied Bundles</relationshipLabel>
    <relationshipName>Applied_Bundles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applied_Bundle__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity of bundles ordered</description>
    <label>Quantity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Applied_Bundle__c/fields/Sales_Discount__c.field-meta.xml
<CustomField>
    <fullName>Sales_Discount__c</fullName>
    <description>Discretionary discount offered by Sales staff.</description>
    <label>Sales Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applied_Bundle__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <description>Price after discounts and quantity adjustments</description>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bundle__c/Bundle__c.object-meta.xml
<CustomObject>
    <description>Represents a bundle of products that are marketed, priced and sold as a unit</description>
    <label>Bundle</label>
    <nameField>
        <label>Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle__c/fields/Storage_Type__c.field-meta.xml
<CustomField>
    <fullName>Storage_Type__c</fullName>
    <description>The storage type for the item in this single-product bundle.</description>
    <inlineHelpText>The storage type for the item in this single-product bundle.</inlineHelpText>
    <label>Storage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Storage_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bundle__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Affects how bundles are shown and filtered in the Order Builder.</description>
    <inlineHelpText>Single-Product bundles contain storage + processing for one service.  Multi-Product bundles contain two or more services or products.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single-Product</fullName>
            </value>
            <value>
                <fullName>Multi-Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bundle__c/fields/Valid_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_From_Date__c</fullName>
    <label>Valid From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bundle__c/fields/Valid_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_To_Date__c</fullName>
    <label>Valid To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bundle_Member__c/Bundle_Member__c.object-meta.xml
<CustomObject>
    <description>Join object that relates Products to Bundles</description>
    <label>Bundle Member</label>
    <nameField>
        <displayFormat>BMN-{000000}</displayFormat>
        <label>Bundle Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Member__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <description>The bundle that this bundle-member applied to</description>
    <label>Bundle</label>
    <referenceTo>Bundle__c</referenceTo>
    <relationshipLabel>Bundle Members</relationshipLabel>
    <relationshipName>Bundle_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bundle_Member__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product that this bundle member adds. Ideally this would be required at the field level, but Product lookups cannot be made required -- SF limitation.</description>
    <inlineHelpText>Required!</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Members</relationshipLabel>
    <relationshipName>Bundle_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bundle_Member__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>How many of this line item are represented in the bundle.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/Bundle_Pricebook_Entry__c.object-meta.xml
<CustomObject>
    <label>Bundle Pricebook Entry</label>
    <nameField>
        <displayFormat>BPE-{000000}</displayFormat>
        <label>Pricebook Entry Bundle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Pricebook Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <label>Bundle</label>
    <referenceTo>Bundle__c</referenceTo>
    <relationshipLabel>Bundle Pricebook Entries</relationshipLabel>
    <relationshipName>Bundle_Pricebook_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bundle_Pricebook_Entry__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>Marketing price for the bundle in this pricebook</description>
    <label>List Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>The total of all the list prices of bundles and products in this Opportunity.  Represents the price before any Sales or Marketing discounts are applied.</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marketing_Discount__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Discount__c</fullName>
    <description>A discount that was added via a promotional code or similar.</description>
    <label>Marketing Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Discount__c.field-meta.xml
<CustomField>
    <fullName>Sales_Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sales Discount</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Applied_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Applied_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The bundle that added this product (if applicable)</description>
    <label>Applied Bundle</label>
    <referenceTo>Applied_Bundle__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Marketing_Discount__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Discount__c</fullName>
    <description>A discount that was added via a promotional code or similar.</description>
    <inlineHelpText>A discount that was added via a promotional code or similar.</inlineHelpText>
    <label>Marketing Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Sales_Discount__c.field-meta.xml
<CustomField>
    <fullName>Sales_Discount__c</fullName>
    <description>Discretionary discount offered by Sales staff.</description>
    <inlineHelpText>Discretionary discount offered by Sales staff.</inlineHelpText>
    <label>Sales Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Relationship__c/Product_Relationship__c.object-meta.xml
<CustomObject>
    <description>Allows us to create relationships between products to define things such as suggested upsells or required add-ons.</description>
    <label>Product Relationship</label>
    <nameField>
        <displayFormat>PRN-{000000}</displayFormat>
        <label>Product Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Bundle.cls
public with sharing class Bundle {
    public ID Id;
    public ID opportunityId;
    public ID invoiceId;
    public ID appliedBundleId;
    public String name;
    public String type;
    public Decimal listPrice;
    public Decimal listPriceAtQuantity;
    public Decimal finalPrice; //List price minus sales and marketing discounts
    public Decimal bundleMembersListPriceTotal; //total list price at current quantity
    public List < Product > bundledProducts;
    public Date validFrom;
    public Date validTo;
    public Integer quantity;
    public Decimal marketingDiscountApplied; //via a code
    public Decimal salesDiscountApplied; //via the sales person
    public Decimal combinedDiscounts;
    public Decimal bundleSavings; //the difference between the bundle line items total and the bundle list price
    public Decimal bundleSavingsAtQuantity; 
    public Decimal totalListPriceDiscountableProducts = 0; //the total of just the included products (at base quantity) which are not exempt from discounting - used in discount proportion calculations
    public String storageType; //used for single product bundles to indicate the storage type.  Used in Order Builder to select automated discounts

    public Bundle(){}

    // Loading the basic bundle from defining metadata - not specific to any order
    public Bundle (Bundle__c bundle, Bundle_Pricebook_Entry__c bundlePricebookEntry, Map < ID, Decimal > productListPricesMap, Map < ID, List < Product_Relationship__c >> productsWithRelatedMap) {
        this.Id = bundle.Id;
        this.name = bundle.Name;
        this.type = bundle.Type__c;
        this.storageType = bundle.Storage_Type__c;
        this.listPrice = bundlePricebookEntry.List_Price__c;
        this.listPriceAtQuantity = this.listPrice;
        this.validFrom = bundle.Valid_From_Date__c;
        this.validTo = bundle.Valid_To_Date__c;
        this.marketingDiscountApplied = 0;
        this.salesDiscountApplied = 0;
        this.combinedDiscounts = 0;
        this.finalPrice = this.listPriceAtQuantity + this.combinedDiscounts;
        this.quantity = 1;
        this.bundledProducts = new List < Product >();

        Decimal listPriceAllProductsAtStartingQuantity = 0;
        Decimal listPriceDiscountableProductsAtStartingQuantity = 0;
        for (Bundle_Member__c bundleMember: bundle.Bundle_Members__r) {
            Product product = new Product(bundleMember, productListPricesMap, productsWithRelatedMap);
            listPriceAllProductsAtStartingQuantity += product.listPriceAtQuantity;
            if (product.isDiscountable()) {
                listPriceDiscountableProductsAtStartingQuantity+=product.listPriceAtQuantity;
            }

            this.bundledProducts.add(product);
        }
        this.bundleMembersListPriceTotal = listPriceAllProductsAtStartingQuantity;
        this.totalListPriceDiscountableProducts = listPriceDiscountableProductsAtStartingQuantity;

        // Calculate the implied bundle savings
        this.bundleSavings = this.listPrice - listPriceAllProductsAtStartingQuantity;
        this.bundleSavingsAtQuantity = this.bundleSavings;
        this.updateDiscounts();
        
    }


    // Load a particular bundle given the applied bundle, opportunityLineItems and bundlePricebookEntry
    public Bundle (Applied_Bundle__c appliedBundle, List < SObject > lineItems, Bundle_Pricebook_Entry__c bundlePricebookEntry) {
        this.loadValuesFromAppliedBundle(appliedBundle);
        this.listPrice = bundlePricebookEntry.List_Price__c;
        this.listPriceAtQuantity = this.listPrice * appliedBundle.Quantity__c;

        Decimal listPriceAllProductsAtCurrentQuantity = 0;
        Decimal listPriceAllProductsAtBaseQuantity = 0; //some bundles will include multiples of a given product.

        List < Bundle_Member__c > bundleMembers = [SELECT ID, Product__c, Quantity__c FROM Bundle_Member__c WHERE Bundle__c =:appliedBundle.Bundle__c];
        Map < ID, Bundle_Member__c > bundleMembersByProductId = new Map < ID, Bundle_Member__c >();
        for (Bundle_Member__c mem: bundleMembers) {
            bundleMembersByProductId.put(mem.Product__c, mem);
        }

        // Line items passed in may be either Opportunity Line Items or Invoice Line Items.  The Product constructor works with either
        for (SObject li: lineItems) {
            Product bundleMemberProduct = new Product(li);
            bundleMemberProduct.startingQuantityInBundle = Integer.valueOf(bundleMembersByProductId.get(bundleMemberProduct.Id).Quantity__c);
            this.bundledProducts.add(bundleMemberProduct);
            listPriceAllProductsAtCurrentQuantity+=bundleMemberProduct.listPrice*bundleMemberProduct.quantity;
            listPriceAllProductsAtBaseQuantity+=bundleMemberProduct.listPrice*bundleMemberProduct.startingQuantityInBundle;
            if (bundleMemberProduct.isDiscountable()) {
                this.totalListPriceDiscountableProducts+=(bundleMemberProduct.listPrice*bundleMemberProduct.startingQuantityInBundle);
            }
        }

        this.bundleMembersListPriceTotal = listPriceAllProductsAtCurrentQuantity;
        this.bundleSavings = this.listPrice - listPriceAllProductsAtBaseQuantity;
        this.bundleSavingsAtQuantity = this.listPriceAtQuantity - listPriceAllProductsAtCurrentQuantity;
        this.finalPrice = this.listPriceAtQuantity + this.combinedDiscounts;
        this.updateDiscounts();

    }

    private void loadValuesFromAppliedBundle(Applied_Bundle__c appliedBundle) {
        this.Id = appliedBundle.Bundle__c;
        this.opportunityId = appliedBundle.Opportunity__c;
        this.invoiceId = appliedBundle.Invoice__c;
        this.appliedBundleId = appliedBundle.Id;
        this.name = appliedBundle.Bundle__r.Name;
        this.type = appliedBundle.Bundle__r.Type__c;
        this.storageType = appliedBundle.Bundle__r.Storage_Type__c;
        this.validFrom = appliedBundle.Bundle__r.Valid_From_Date__c;
        this.validTo = appliedBundle.Bundle__r.Valid_To_Date__c;
        this.marketingDiscountApplied = appliedBundle.Marketing_Discount__c;
        this.salesDiscountApplied = appliedBundle.Sales_Discount__c;
        this.combinedDiscounts = this.marketingDiscountApplied + this.salesDiscountApplied;
        this.finalPrice = appliedBundle.Total_Price__c;
        this.quantity = Integer.valueOf(appliedBundle.Quantity__c);
        this.bundledProducts = new List < Product >();
    }

    public void updateDiscounts() {
        Decimal listPriceDiscountableProductsCurrentQuantity = this.totalListPriceDiscountableProducts * this.quantity;
        System.debug('this.quantity: '+this.quantity);
        System.debug('listPriceDiscountableProductsCurrentQuantity: '+listPriceDiscountableProductsCurrentQuantity);
        

        for (Product product: this.bundledProducts) {
            if (product.isDiscountable()) {
                product.proportionOfDiscountableBundleTotal = 0; 
                if (listPriceDiscountableProductsCurrentQuantity!=0) product.proportionOfDiscountableBundleTotal = product.listPriceAtQuantity/listPriceDiscountableProductsCurrentQuantity;
                product.bundleSavingsAtQuantity = product.proportionOfDiscountableBundleTotal * this.bundleSavingsAtQuantity;
                System.debug('this.bundleSavingsAtQuantity: '+this.bundleSavingsAtQuantity);
                System.debug('product.proportionOfDiscountableBundleTotal: '+product.proportionOfDiscountableBundleTotal);
                // Bundle savings at quantity is tricky when the bundle has a different quantity than the products. For example, a Twins bundle where the quantity is one and it contains 2 of a given product.  In this case, the bundlesavings is just the relative proportion of the overall bundle savings, we don't want to inflate it
                product.marketingDiscountApplied = product.proportionOfDiscountableBundleTotal * this.marketingDiscountApplied;
                product.salesDiscountApplied = product.proportionOfDiscountableBundleTotal * this.salesDiscountApplied;
            }
        }
    }

    public void updateSobjs(String orderContext) {
        System.debug('orderContext: '+orderContext);
        List < SObject > sobjsToUpdate = new List < SObject >();
        
        for (Product product: this.bundledProducts) {
            if (orderContext=='Opportunity') {
                OpportunityLineItem oli = product.asOppLineItem();
                sobjsToUpdate.add(oli);
            } else {
                sobjsToUpdate.add(product.asInvoiceLineItem());
            }
        }
        sobjsToUpdate.add(this.asAppliedBundle(orderContext));
        System.debug('sobjsToUpdate: '+JSON.serialize(sobjsToUpdate));
        update sobjsToUpdate;

    }

    public void applyDiscount(Discount discount) {
        // figure out the percentage if a whole-dollar discount
        Decimal totalDiscountAmount;
        if (discount.method=='Amount') {
            totalDiscountAmount = discount.amount * this.quantity;
        } else {
            totalDiscountAmount = discount.percentage * this.listPrice; //list price will have already been adjusted for quantity & bundle savings
            discount.amount = totalDiscountAmount;
        }

        totalDiscountAmount = totalDiscountAmount * -1;

        // put it in the correct field, sales or marketing
        if (String.isBlank(discount.marketingCode)) {
            this.salesDiscountApplied = totalDiscountAmount;
        } else {
            this.marketingDiscountApplied = totalDiscountAmount;
        }

        this.updateDiscounts(); //updates the individual product line items with discount data

    }

    public void clearDiscountAmounts() {
        this.salesDiscountApplied = 0;
        this.marketingDiscountApplied = 0;
        for (Product product: this.bundledProducts) {
            product.clearDiscountAmounts();
        }
    }

    public Applied_Bundle__c asAppliedBundle (String orderContext) {
        Applied_Bundle__c appliedBundle = new Applied_Bundle__c (
            Id = this.appliedBundleId,
            Bundle__c = this.Id,
            Marketing_Discount__c = this.marketingDiscountApplied,
            Sales_Discount__c = this.salesDiscountApplied,
            Total_Price__c = this.finalPrice,
            Quantity__c = this.quantity
        );

        if (orderContext=='Opportunity') {
            appliedBundle.Opportunity__c = this.opportunityId;
        } else {
            appliedBundle.Invoice__c = this.invoiceId;
        }

        return appliedBundle;
        
    }
}